<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);NU1603</NoWarn>
    <UserSecretsId>f5a0e82c-0c66-43cc-8b0e-a36b06f4976a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.DevUI" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting.OpenAI" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.Client\Aspire.Client.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Agents\Agents.csproj" />
    <ProjectReference Include="..\Agents.CSharp\Agents.CSharp.csproj" />
  </ItemGroup>

</Project>
