<Project Sdk="Aspire.AppHost.Sdk/13.5.0-preview.1.26363.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brain.Kernel.Host\Brain.Kernel.Host.csproj" />
    <ProjectReference Include="..\..\edge\Brain.Mcp\Brain.Mcp.csproj" />
    <ProjectReference Include="..\..\edge\Brain.UiGateway\Brain.UiGateway.csproj" />
  </ItemGroup>

</Project>
