<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Aspire AppHost integration for the DigitalBrain Flutter module.</Description>
    <RootNamespace>DigitalBrain.Flutter.Aspire.Hosting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DigitalBrain.Modules.Flutter.Tests.E2E" />
    <ProjectReference Include="../Flutter/DigitalBrain.Modules.Flutter.csproj" />
    <ProjectReference Include="../../DigitalBrain/Aspire.Hosting/DigitalBrain.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
