using System.ComponentModel;
using DigitalBrain.Abstractions.Entities;
using DigitalBrain.Abstractions.Identity;
using DigitalBrain.AI;
using Microsoft.Extensions.AI;

namespace DigitalBrain.SmartPrompt;

internal sealed class BehaviorToolSource(
    IGrainFactory grains,
    IBehaviorFeatureGenerator generator) : IAgentToolSource
{
    public IReadOnlyList<AIFunction> ToolsFor(OwnerId owner)
    {
        async Task<string> GenerateBehavior(
            [Description("Lowercase behavior identifier using letters, numbers, and hyphens")] string name,
            [Description("Natural-language description of the desired automation")] string request,
            CancellationToken cancellationToken)
        {
            if (!ValidName(name))
            {
                return "name must use only lowercase letters, numbers, and hyphens.";
            }
            var generated = await generator.Generate(request, cancellationToken);
            if (!generated.Compilation.Success)
            {
                return "Gemma produced a feature that did not compile:\n" + string.Join("\n",
                    generated.Compilation.Diagnostics.Select(d => $"line {d.Line}: {d.Message}"));
            }
            var definition = Definition(owner, name);
            await definition.Save(generated.Source);
            await Catalog(owner).Add(name);
            var report = await definition.Test();
            if (report.AllGreen)
            {
                await definition.Activate();
            }
            return report.AllGreen
                ? $"Behavior '{name}' was generated by {generated.Model}, tested, and activated.\n{generated.Source}"
                : $"Behavior '{name}' was saved but its tests failed: {string.Join("; ", report.Failures)}";
        }

        async Task<string> RunBehaviorExample(
            [Description("One of the built-in behavior names shown in the Behaviors tab")] string name,
            CancellationToken cancellationToken)
        {
            var example = BehaviorExamples.Find(name);
            if (example is null)
            {
                return $"Unknown example '{name}'. Available: {string.Join(", ", BehaviorExamples.All.Select(x => x.Name))}.";
            }
            var definition = Definition(owner, name);
            var state = await definition.Read();
            if (state is null)
            {
                await definition.Save(example.Source);
                await definition.Test();
                await definition.Activate();
            }
            var behaviorEvent = FakeBehaviorEvents.Create(name);
            await grains.GetGrain<IBehaviorIngress>(BehaviorIngressNames.Shared).Publish(behaviorEvent);
            return $"Ran '{name}' with {FakeBehaviorEvents.Describe(behaviorEvent)}.";
        }

        return
        [
            AIFunctionFactory.Create(GenerateBehavior, new AIFunctionFactoryOptions
            {
                Name = "generate_behavior_feature",
                Description = "Compile a requested automation into a Reqnroll-compatible Gherkin Behavior, run its paired tests, and activate it only when green.",
            }),
            AIFunctionFactory.Create(RunBehaviorExample, new AIFunctionFactoryOptions
            {
                Name = "run_behavior_example",
                Description = "Run one of the eight built-in Behaviors with deterministic fake provider data so the owner can safely preview it.",
            }),
        ];
    }

    private IBehaviorDefinition Definition(OwnerId owner, string name)
        => grains.GetGrain<IBehaviorDefinition>(EntityId.For<IBehaviorDefinition>(owner, name).ToGrainId());

    private IBehaviorCatalog Catalog(OwnerId owner)
        => grains.GetGrain<IBehaviorCatalog>(EntityId.For<IBehaviorCatalog>(owner, "catalog").ToGrainId());

    private static bool ValidName(string name)
        => !string.IsNullOrWhiteSpace(name)
           && name.All(static c => char.IsAsciiLetterLower(c) || char.IsDigit(c) || c == '-');
}
