<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <StartupObject>DigitalBrain.Platform.Tests.E2E.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
    <ProjectReference Include="../../../../Aspire/DigitalBrain.Aspire.Server/DigitalBrain.Aspire.Server.csproj" />
    <None Include="../DigitalBrain.Platform.Tests.Unit/Identity/LegacyState/*.orleans" Link="LegacyState/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
