<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Kernel/DigitalBrain/DigitalBrain.csproj" />
    <ProjectReference Include="../Kernel/DigitalBrain.Client/DigitalBrain.Client.csproj" />
  </ItemGroup>
</Project>
