using System.Text.Json.Serialization;

namespace DigitalBrain.Protocol;

[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(uint))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DateTimeOffset))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(Synapse))]
[JsonSerializable(typeof(NeuronId))]
[JsonSerializable(typeof(Checkpoint))]
[JsonSerializable(typeof(NeuronActivated))]
[JsonSerializable(typeof(DistributedAppStarted))]
[JsonSerializable(typeof(RestartResource))]
[JsonSerializable(typeof(StartDistributedApp))]
[JsonSerializable(typeof(ListPublished))]
[JsonSerializable(typeof(CreateNeuronRequest))]
[JsonSerializable(typeof(NeuronCodeGenerated))]
[JsonSerializable(typeof(NeuronTelemetry))]
[JsonSerializable(typeof(WiringOptimizationProposed))]
[JsonSerializable(typeof(DemoMessageSynapse))]
[JsonSerializable(typeof(ExperienceUsed))]
[JsonSerializable(typeof(LlmPrompt))]
[JsonSerializable(typeof(LlmResponse))]
[JsonSerializable(typeof(CreateSimpleApp))]
[JsonSerializable(typeof(SimpleAppCreated))]
[JsonSerializable(typeof(SystemLaunched))]
[JsonSerializable(typeof(SystemStatusChanged))]
[JsonSerializable(typeof(FixProposal))]
[JsonSerializable(typeof(SimulationResult))]
[JsonSerializable(typeof(PublishToMarketplace))]
[JsonSerializable(typeof(InstallFromMarketplace))]
[JsonSerializable(typeof(NeuroPackInstalled))]
[JsonSerializable(typeof(PublishedList))]
[JsonSerializable(typeof(CommissionTaken))]
[JsonSerializable(typeof(BranchCreated))]
[JsonSerializable(typeof(KernelTaskCreated))]
[JsonSerializable(typeof(KernelTaskStarted))]
[JsonSerializable(typeof(KernelTaskProgress))]
[JsonSerializable(typeof(KernelTaskCompleted))]
[JsonSerializable(typeof(KernelTaskCancelled))]
[JsonSerializable(typeof(RunKernelTask))]
[JsonSerializable(typeof(CancelKernelTask))]
[JsonSerializable(typeof(InoRequest))]
[JsonSerializable(typeof(InoResponse))]
[JsonSerializable(typeof(MemorySummary))]
[JsonSerializable(typeof(InoCodeEdit))]
[JsonSerializable(typeof(InoCodeRun))]
[JsonSerializable(typeof(NuGetCommand))]
[JsonSerializable(typeof(NuGetResult))]
[JsonSerializable(typeof(ArchitectRequest))]
[JsonSerializable(typeof(ArchitectReport))]
[JsonSerializable(typeof(ArchitectResult))]
[JsonSerializable(typeof(ClosedLoopRequest))]
[JsonSerializable(typeof(InoCodeSave))]
[JsonSerializable(typeof(InoCodeExecute))]
[JsonSerializable(typeof(InoCodeApplySkill))]
[JsonSerializable(typeof(SkillContextInjected))]
[JsonSerializable(typeof(ContextUpdate))]
[JsonSerializable(typeof(DbConnect))]
[JsonSerializable(typeof(DbQuery))]
[JsonSerializable(typeof(FilterChanged))]
[JsonSerializable(typeof(ClusterActivity))]
[JsonSerializable(typeof(ThreeDGraphUpdate))]
[JsonSerializable(typeof(VisualizeDataRequest))]
[JsonSerializable(typeof(DataChartGenerated))]
[JsonSerializable(typeof(DataChartFailed))]
[JsonSerializable(typeof(WidgetTreeInspected))]
[JsonSerializable(typeof(UIModificationProposed))]
[JsonSerializable(typeof(SystemModificationProposed))]
[JsonSerializable(typeof(ClosedLoopCompleted))]
// Foundry synapses
[JsonSerializable(typeof(GenerateCode))]
[JsonSerializable(typeof(CodeGenerated))]
[JsonSerializable(typeof(RunGeneratedCode))]
[JsonSerializable(typeof(CodeRunResult))]
[JsonSerializable(typeof(DeployGeneratedCode))]
[JsonSerializable(typeof(CodeBuilt))]
[JsonSerializable(typeof(SiloRestartRequested))]
[JsonSerializable(typeof(FoundryRequest))]
[JsonSerializable(typeof(FoundryCheckpointed))]
[JsonSerializable(typeof(FoundryCompleted))]
[JsonSerializable(typeof(FoundryRolledBack))]
// UI surface synapses
[JsonSerializable(typeof(UiSurface))]
[JsonSerializable(typeof(ChartSpec))]
[JsonSerializable(typeof(AuthButtonSurface))]
[JsonSerializable(typeof(ListSurface))]
[JsonSerializable(typeof(IdeSurface))]
// SDK integration-neuron synapses
[JsonSerializable(typeof(GitCommitted))]
[JsonSerializable(typeof(GitReverted))]
// Distribution / embodiment
[JsonSerializable(typeof(PackEmission))]
// Awesome / software-engineering review
[JsonSerializable(typeof(ReviewRequest))]
[JsonSerializable(typeof(ReviewProjectRequest))]
[JsonSerializable(typeof(ReviewResult))]
public partial class JournalJsonContext : JsonSerializerContext;
