<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Data.Tables" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Journaling.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Reminders.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\modules\DigitalBrain.Modules.AI\DigitalBrain.Modules.AI.csproj" />
    <ProjectReference Include="..\..\modules\DigitalBrain.Modules.Google\DigitalBrain.Modules.Google.csproj" />
    <ProjectReference Include="..\..\modules\DigitalBrain.Modules.Salesforce\DigitalBrain.Modules.Salesforce.csproj" />
    <ProjectReference Include="..\..\samples\DigitalBrain.AccountEnrichment\DigitalBrain.AccountEnrichment.csproj" />
    <ProjectReference Include="..\..\src\DigitalBrain.Kernel\DigitalBrain.Kernel.csproj" />
    <ProjectReference Include="..\..\src\DigitalBrain.SourceGeneration\DigitalBrain.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
