<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>Ino.Identity</RootNamespace>
    <AssemblyName>Ino.Identity</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ino.Core\Ino.Core.csproj" />
    <ProjectReference Include="..\Ino.Core.Hosting\Ino.Core.Hosting.csproj" />
    <ProjectReference Include="..\Ino.ServiceDefaults\Ino.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Ino.Llm.Xai\Ino.Llm.Xai.csproj" />
  </ItemGroup>

</Project>
