version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      aspire:
        patterns:
          - "Aspire.*"
          - "CommunityToolkit.Aspire.*"
      orleans:
        patterns:
          - "Microsoft.Orleans.*"
      microsoft:
        patterns:
          - "Microsoft.Extensions.*"
          - "Microsoft.AspNetCore.*"
          - "Microsoft.NET.Test.Sdk"
      azure:
        patterns:
          - "Azure.*"
      opentelemetry:
        patterns:
          - "OpenTelemetry.*"
      grpc:
        patterns:
          - "Grpc.*"
      google:
        patterns:
          - "Google.*"
      test:
        patterns:
          - "xunit*"
          - "coverlet.*"
          - "Reqnroll*"
          - "Xunit.*"
    open-pull-requests-limit: 15

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "weekly"
    groups:
      flutter-deps:
        patterns:
          - "*"