using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;

namespace DigitalBrain.SourceGen;

[Generator]
public sealed class DigitalBrainSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Each class can implement many IHandle<>/IEmit<> interfaces; collect every one, then flatten across classes.
        var handlerInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetHandlerInfos(ctx, cancellationToken))
            .Where(static infos => infos.Length > 0)
            .SelectMany(static (infos, _) => infos)
            .Collect();

        context.RegisterSourceOutput(handlerInfos, static (ctx, infos) =>
        {
            var source = GenerateManifest(infos);
            ctx.AddSource("DispatchManifest.g.cs", source);
        });
    }

    private static ImmutableArray<HandlerInfo> GetHandlerInfos(GeneratorSyntaxContext ctx, CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, cancellationToken) is not INamedTypeSymbol symbol)
            return ImmutableArray<HandlerInfo>.Empty;

        var neuronType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Interface name match (gen has no direct Core ref; semantic resolution from the user compilation).
        // A synapse may be reachable through several interface paths, so dedupe on (synapse, isHandle).
        var builder = ImmutableArray.CreateBuilder<HandlerInfo>();
        var seen = new HashSet<(string Synapse, bool IsHandle)>();
        foreach (var iface in symbol.AllInterfaces)
        {
            bool isHandle = iface.Name == "IHandle";
            bool isEmit = iface.Name == "IEmit";
            if ((!isHandle && !isEmit) || !iface.IsGenericType || iface.TypeArguments.Length != 1)
                continue;

            var synapseType = iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (seen.Add((synapseType, isHandle)))
                builder.Add(new HandlerInfo(neuronType, synapseType, isHandle));
        }

        return builder.ToImmutable();
    }

    private static string GenerateManifest(ImmutableArray<HandlerInfo> infos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DigitalBrain.SourceGen;");
        sb.AppendLine();
        sb.AppendLine("public static class DispatchManifest");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly (string Neuron, string Synapse)[] KnownHandlers = new[]");
        sb.AppendLine("    {");

        bool any = false;
        foreach (var info in infos)
        {
            if (info.IsHandle)
            {
                any = true;
                sb.AppendLine($"        (\"{info.NeuronType}\", \"{info.SynapseType}\"),");
            }
        }

        if (!any)
        {
            sb.AppendLine("        // No IHandle<> in this compilation.");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    // Catalog for contracts/constellation (slice 11): includes both IHandle (IsHandle=true) and IEmit (false) for static analysis of neurons/synapses.");
        sb.AppendLine("    // Complements KnownHandlers + pre-resolved invokers. Dynamic installs still grow via reflection fallback.");
        sb.AppendLine("    public static readonly (string Neuron, string Synapse, bool IsHandle)[] KnownContracts = new[]");
        sb.AppendLine("    {");

        bool anyC = false;
        foreach (var info in infos)
        {
            anyC = true;
            sb.AppendLine($"        (\"{info.NeuronType}\", \"{info.SynapseType}\", {(info.IsHandle ? "true" : "false")}),");
        }

        if (!anyC)
        {
            sb.AppendLine("        // No IHandle/IEmit implementations found in this compilation (or only dynamic).");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    // Pre-resolved handler info (slice 9): MethodInfo construction captured here (in generated static cctor, runs once on manifest load).");
        sb.AppendLine("    // Neuron dispatch fast-path for static known uses this to skip MakeGenericType + GetMethod entirely.");
        sb.AppendLine("    // Dynamic (new installs) still falls back to full GetInterfaces scan in Neuron.");
        sb.AppendLine("    private static readonly System.Collections.Frozen.FrozenDictionary<(System.Type, System.Type), System.Reflection.MethodInfo> _preResolvedHandlers;");
        sb.AppendLine();
        sb.AppendLine("    static DispatchManifest()");
        sb.AppendLine("    {");
        sb.AppendLine("        var map = new System.Collections.Generic.Dictionary<(System.Type, System.Type), System.Reflection.MethodInfo>();");

        int idx = 0;
        foreach (var info in infos)
        {
            if (info.IsHandle)
            {
                // Use the fully-qualified display strings (global::...) directly in emitted typeof for compile-time known concrete types.
                sb.AppendLine($"        var nt{idx} = typeof({info.NeuronType});");
                sb.AppendLine($"        var st{idx} = typeof({info.SynapseType});");
                sb.AppendLine($"        var i{idx} = typeof(global::DigitalBrain.Protocol.IHandle<>).MakeGenericType(st{idx});");
                sb.AppendLine($"        map[(nt{idx}, st{idx})] = i{idx}.GetMethod(nameof(global::DigitalBrain.Protocol.IHandle<{info.SynapseType}>.HandleAsync))!;");
            }
            idx++;
        }

        sb.AppendLine("        _preResolvedHandlers = System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(map);");

        // Invoker emission (slice 10) generalized for Neuron + any future base (no hard Neuron cast).
        // We populate a general Func<object, Synapse, CT, Task> using the already-resolved MethodInfo (safe for all hosts).
        // The Dispatch will prefer pre-resolved MethodInfo for known; this keeps the catalog + fast MethodInfo path working for Creator, Memory, Durable grains etc.
        sb.AppendLine("        var invMap = new System.Collections.Generic.Dictionary<(System.Type, System.Type), System.Func<object, global::DigitalBrain.Protocol.Domain.Events.Synapse, System.Threading.CancellationToken, System.Threading.Tasks.Task>>();");
        idx = 0;
        foreach (var info in infos)
        {
            if (info.IsHandle)
            {
                sb.AppendLine($"        var ntI{idx} = typeof({info.NeuronType});");
                sb.AppendLine($"        var stI{idx} = typeof({info.SynapseType});");
                sb.AppendLine($"        var mi{idx} = global::DigitalBrain.SourceGen.DispatchManifest.GetPreResolvedHandleMethod(ntI{idx}, stI{idx})!; // non-null: only emitted for known manifest entries");
                sb.AppendLine($"        var inv{idx} = (System.Func<object, global::DigitalBrain.Protocol.Domain.Events.Synapse, System.Threading.CancellationToken, System.Threading.Tasks.Task>)((n, s, cancellationToken) => (Task)mi{idx}.Invoke(n, new object[] {{ s, cancellationToken }})!);");
                sb.AppendLine($"        invMap[(ntI{idx}, stI{idx})] = inv{idx};");
            }
            idx++;
        }
        sb.AppendLine("        _preResolvedInvokers = System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(invMap);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static System.Reflection.MethodInfo? GetPreResolvedHandleMethod(System.Type neuronType, System.Type synapseType)");
        sb.AppendLine("        => _preResolvedHandlers.TryGetValue((neuronType, synapseType), out var m) ? m : null;");
        sb.AppendLine();
        sb.AppendLine("    // Pre-resolved invoker delegates (generalized): work for Neuron and any IHandle host. Uses MethodInfo under the hood for safety.");
        sb.AppendLine("    private static readonly System.Collections.Frozen.FrozenDictionary<(System.Type, System.Type), System.Func<object, global::DigitalBrain.Protocol.Domain.Events.Synapse, System.Threading.CancellationToken, System.Threading.Tasks.Task>> _preResolvedInvokers;");
        sb.AppendLine();
        sb.AppendLine("    public static System.Func<object, global::DigitalBrain.Protocol.Domain.Events.Synapse, System.Threading.CancellationToken, System.Threading.Tasks.Task>? GetPreResolvedInvoker(System.Type neuronType, System.Type synapseType)");
        sb.AppendLine("        => _preResolvedInvokers.TryGetValue((neuronType, synapseType), out var d) ? d : null;");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class HandlerInfo
    {
        public string NeuronType { get; }
        public string SynapseType { get; }
        public bool IsHandle { get; }

        public HandlerInfo(string neuronType, string synapseType, bool isHandle)
        {
            NeuronType = neuronType;
            SynapseType = synapseType;
            IsHandle = isHandle;
        }
    }
}
