<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DigitalBrain.Core.Tests.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Identity/LegacyState/*.orleans" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="..\Sdk\DigitalBrain.Modules.Kernel.Sdk\DigitalBrain.Modules.Sdk.csproj" />
    <ProjectReference Include="../Platform/DigitalBrain.Platform/DigitalBrain.Platform.csproj" />
    <ProjectReference Include="..\Aspire\DigitalBrain.Kernel.Aspire.Hosting\DigitalBrain.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>

