<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA2007;CA1515;CA1812;CA1822</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Orleans.Serialization.SystemTextJson" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\core\kernel\DigitalBrain\DigitalBrain.csproj" />
    <ProjectReference Include="..\..\..\core\testing\DigitalBrain.Testing\DigitalBrain.Testing.csproj" />
    <ProjectReference Include="..\DigitalBrain.Modules.Chat\DigitalBrain.Modules.Chat.csproj" />
    <ProjectReference Include="..\..\ai\DigitalBrain.Modules.AI\DigitalBrain.Modules.AI.csproj" />
  </ItemGroup>
</Project>
