<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../../../Testing/DigitalBrain.Testing.Module/DigitalBrain.Testing.Module.csproj" />
    <ProjectReference Include="../../DigitalBrain.Modules.Microsoft.CSharp/DigitalBrain.Modules.Microsoft.CSharp.csproj" />
    <ProjectReference Include="../../../../../DigitalBrain/Sdk/DigitalBrain.Sdk/DigitalBrain.Sdk.csproj" />
    <ProjectReference Include="../../../../../DigitalBrain/Platform/DigitalBrain.Platform/DigitalBrain.Platform.csproj" />
    <ProjectReference Include="../../DigitalBrain.Modules.Microsoft.CSharp.Sandbox/DigitalBrain.Modules.Microsoft.CSharp.Sandbox.csproj" />
    <ProjectReference Include="../../../../Time/DigitalBrain.Modules.Time.Contracts/DigitalBrain.Modules.Time.Contracts.csproj" />
    <ProjectReference Include="../../../../DigitalBrain/Registry/DigitalBrain.Modules.Registry/DigitalBrain.Modules.Registry.csproj" />
  </ItemGroup>
  <ItemGroup><Using Include="DigitalBrain.Testing.Module" /></ItemGroup>
</Project>
