<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Azure deployment for the ClickHouse module: the ClickHouse server.</Description>
    <RootNamespace>DigitalBrain.Modules.ClickHouse.Deployment</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../DigitalBrain/Deployment/DigitalBrain.Deployment/DigitalBrain.Deployment.csproj" />
    <ProjectReference Include="../DigitalBrain.Modules.ClickHouse/DigitalBrain.Modules.ClickHouse.csproj" />
  </ItemGroup>
</Project>
