<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Reqnroll" Version="3.3.4" />
    <PackageVersion Include="Reqnroll.xunit.v3" Version="3.3.4" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Orleans.Client" Version="10.2.2-rc.2" />
    <PackageVersion Include="Microsoft.Orleans.Core.Abstractions" Version="10.2.2-rc.2" />
    <PackageVersion Include="Microsoft.Orleans.Journaling" Version="10.2.2-rc.2.alpha.1" />
    <PackageVersion Include="Microsoft.Orleans.Reminders" Version="10.2.2-rc.2" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.2.2-rc.2" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2-rc.2" />
    <PackageVersion Include="Microsoft.Orleans.TestingHost" Version="10.2.2-rc.2" />
  </ItemGroup>
</Project>
