<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Aspire AppHost integration for the DigitalBrain Salesforce module.</Description>
    <RootNamespace>DigitalBrain.Salesforce.Aspire.Hosting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DigitalBrain.Modules.Salesforce/DigitalBrain.Modules.Salesforce.csproj" />
    <ProjectReference Include="../../DigitalBrain/Kernel/Aspire/DigitalBrain.Kernel.Aspire.Hosting/DigitalBrain.Kernel.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
