<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Microsoft neuron contracts.</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>DigitalBrain.Microsoft</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../DigitalBrain/Contracts/DigitalBrain.Contracts.csproj" />
  </ItemGroup>
</Project>
