<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>DigitalBrain.Testing.Module.Tests.Unit</RootNamespace></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <ProjectReference Include="../../DigitalBrain.Testing.Module/DigitalBrain.Testing.Module.csproj" />
    <None Update="Identity/LegacyState/*.orleans" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
