<Project Sdk="Aspire.AppHost.Sdk/13.5.0-preview.1.26376.5">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);MSB3277;NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\core\aspire\DigitalBrain.Aspire.Hosting\DigitalBrain.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\..\..\src\core\behaviors\DigitalBrain.Behaviors.Runtime\DigitalBrain.Behaviors.Runtime.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\..\..\os\DigitalBrain.OS.Host\DigitalBrain.OS.Host.csproj" />
    <ProjectReference Include="..\..\..\..\os\DigitalBrain.OS.BehaviorHost\DigitalBrain.OS.BehaviorHost.csproj" />
  </ItemGroup>
</Project>
