<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DigitalBrain.Testing</RootNamespace>
    <NoWarn>$(NoWarn);ORLEANSEXP005;CA2007;CA1812</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalBrain.Core\DigitalBrain.Core.csproj" />
    <ProjectReference Include="..\DigitalBrain.Access\DigitalBrain.Access.csproj" />
    <ProjectReference Include="..\DigitalBrain.Hosting\DigitalBrain.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Journaling" />
    <PackageReference Include="Microsoft.Orleans.Reminders" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>
</Project>
