<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../Testing/Integration.Tests.props" />
  <PropertyGroup>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Flutter/DigitalBrain.Modules.Flutter.csproj" />
  </ItemGroup>
</Project>
