<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>DigitalBrain.Telegram</RootNamespace></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Contracts/DigitalBrain.Modules.Telegram.Contracts.csproj" />
    <ProjectReference Include="../../../Kernel/DigitalBrain/DigitalBrain.csproj" />
    <ProjectReference Include="../../Time/Contracts/DigitalBrain.Modules.Time.Contracts.csproj" />
    <ProjectReference Include="../../UI/DigitalBrain.Modules.UI.Contracts/DigitalBrain.Modules.UI.Contracts.csproj" />
  </ItemGroup>
</Project>
