// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripRadar.Server.Db;

#nullable disable

namespace TripRadar.Server.Db.Migrations
{
    [DbContext(typeof(SetupDbContext))]
    [Migration("20260106104245_AddTelegramUserIdToUserProfiles")]
    partial class AddTelegramUserIdToUserProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TripRadar.Server")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripRadar.Server.Db.Models.Airports", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AirportId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("AirportId");

                    b.ToTable("Airports", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.BillingPeriods", b =>
                {
                    b.Property<int>("BillingPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillingPeriodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("BillingPeriodId");

                    b.ToTable("BillingPeriods", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Countries", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Currencies", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurrencyId"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.DiscountTypes", b =>
                {
                    b.Property<int>("DiscountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("DiscountTypeId");

                    b.ToTable("DiscountTypes", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Domains", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DomainId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("DomainId");

                    b.ToTable("Domains", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.FeedbackCategories", b =>
                {
                    b.Property<int>("FeedbackCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FeedbackCategoryId");

                    b.ToTable("FeedbackCategories", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Feedbacks", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FeedbackId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Languages", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Locations", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<int?>("GoogleId")
                        .HasColumnType("integer");

                    b.Property<int?>("GoogleParentId")
                        .HasColumnType("integer");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Reach")
                        .HasColumnType("integer");

                    b.Property<string>("RowId")
                        .HasColumnType("varchar(24)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.OverageBillingRecords", b =>
                {
                    b.Property<long>("OverageBillingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OverageBillingRecordId"));

                    b.Property<DateTime?>("BilledAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBilled")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OverageTokensUsed")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ProcessingId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("StripeInvoiceId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("TokenUnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("UsageTimestamp")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("OverageBillingRecordId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("OverageBillingRecords", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.OveragePricing", b =>
                {
                    b.Property<int>("OveragePricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OveragePricingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PricePerToken")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("TierId")
                        .HasColumnType("integer");

                    b.HasKey("OveragePricingId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TierId");

                    b.ToTable("OveragePricing", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.PreferenceTypes", b =>
                {
                    b.Property<int>("PreferenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PreferenceTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("ValidationSchema")
                        .HasColumnType("jsonb");

                    b.HasKey("PreferenceTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PreferenceTypes", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Prices", b =>
                {
                    b.Property<long>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PriceId"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("StripeId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TierId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.HasKey("PriceId");

                    b.HasIndex("BillingPeriodId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TierId");

                    b.ToTable("Prices", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.PromoCodeUsages", b =>
                {
                    b.Property<long>("PromoCodeUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PromoCodeUsageId"));

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PromoCodeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PromoCodeUsageId");

                    b.ToTable("PromoCodeUsages", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.PromoCodes", b =>
                {
                    b.Property<long>("PromoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PromoCodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DiscountTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsagePerUser")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.HasKey("PromoCodeId");

                    b.ToTable("PromoCodes", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledCurrencyExchangeQueries", b =>
                {
                    b.Property<long>("ScheduledCurrencyExchangeQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledCurrencyExchangeQueryId"));

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long?>("ScheduledExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SelectedColumns")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetCurrencies")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledCurrencyExchangeQueryId");

                    b.HasIndex("ScheduledExecutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledCurrencyExchangeQueries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledEventQueries", b =>
                {
                    b.Property<long>("ScheduledEventQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledEventQueryId"));

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long?>("ScheduledExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SelectedColumns")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledEventQueryId");

                    b.HasIndex("ScheduledExecutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledEventQueries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledExecutions", b =>
                {
                    b.Property<long>("ScheduledExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledExecutionId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("NextExecutionTime")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("TripVaultId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledExecutionId");

                    b.HasIndex("TripVaultId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledExecutions", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledFlightQueries", b =>
                {
                    b.Property<long>("ScheduledFlightQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledFlightQueryId"));

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long?>("ScheduledExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SelectedColumns")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledFlightQueryId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("ScheduledExecutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledFlightQueries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledHotelQueries", b =>
                {
                    b.Property<long>("ScheduledHotelQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledHotelQueryId"));

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("ScheduledExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SelectedColumns")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledHotelQueryId");

                    b.HasIndex("ScheduledExecutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledHotelQueries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledLocalPlacesQueries", b =>
                {
                    b.Property<long>("ScheduledLocalPlacesQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledLocalPlacesQueryId"));

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long?>("ScheduledExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SelectedColumns")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledLocalPlacesQueryId");

                    b.HasIndex("ScheduledExecutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledLocalPlacesQueries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledWeatherQueries", b =>
                {
                    b.Property<long>("ScheduledWeatherQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledWeatherQueryId"));

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<double?>("Latitude")
                        .HasColumnType("decimal(8,6)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<long?>("ScheduledExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SelectedColumns")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduledWeatherQueryId");

                    b.HasIndex("ScheduledExecutionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledWeatherQueries", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ServiceTokenCosts", b =>
                {
                    b.Property<int>("ServiceTokenCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceTokenCostId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ServiceTokenCostId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ServiceTokenCosts", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ServiceTypes", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("ServiceTypes", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Tiers", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TokensPerMonthLimit")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TierId");

                    b.ToTable("Tiers", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.TripQueryHistories", b =>
                {
                    b.Property<long>("TripQueryHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TripQueryHistoryId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("QueryParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("TripVaultId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("TripQueryHistoryId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TripVaultId", "CreatedOn")
                        .IsDescending(false, true);

                    b.ToTable("TripQueryHistories", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.TripVaults", b =>
                {
                    b.Property<long>("TripVaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TripVaultId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.HasKey("TripVaultId");

                    b.HasIndex("OwnerId");

                    b.ToTable("TripVaults", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserMonthlyTokenCounts", b =>
                {
                    b.Property<long>("UserMonthlyTokenCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserMonthlyTokenCountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverageTokensConsumed")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TokensConsumed")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("UserMonthlyTokenCountId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMonthlyTokenCounts", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserPreferences", b =>
                {
                    b.Property<long>("UserPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserPreferenceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferenceTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserPreferenceId");

                    b.HasIndex("PreferenceTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserProfiles", b =>
                {
                    b.Property<long>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserProfileId"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiry")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("EmailHash")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsernameHash")
                        .HasColumnType("varchar(64)");

                    b.HasKey("UserProfileId");

                    b.HasIndex("CountryId");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.HasIndex("LanguageId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UsernameHash")
                        .IsUnique();

                    b.ToTable("UserProfiles", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserSubscriptions", b =>
                {
                    b.Property<long>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserSubscriptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("DeferredDowngradeJobId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayAsYouGoEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("PendingTierId")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("SubscriptionExpirationTime")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("PendingTierId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Users", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<bool>("AllowsMarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<bool>("HasDataStorageConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("PromoCodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TierId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TIMESTAMPTZ");

                    b.HasKey("UserId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("TierId");

                    b.ToTable("Users", "TripRadar.Server");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Feedbacks", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.FeedbackCategories", "Category")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.OverageBillingRecords", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Currencies", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.ServiceTypes", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("ServiceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.OveragePricing", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Currencies", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Tiers", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.PreferenceTypes", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ServiceTypes", "ServiceTypes")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceTypes");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Prices", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.BillingPeriods", "BillingPeriod")
                        .WithMany()
                        .HasForeignKey("BillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Currencies", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Tiers", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingPeriod");

                    b.Navigation("Currency");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledCurrencyExchangeQueries", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ScheduledExecutions", "ScheduledExecution")
                        .WithMany()
                        .HasForeignKey("ScheduledExecutionId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledExecution");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledEventQueries", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ScheduledExecutions", "ScheduledExecution")
                        .WithMany()
                        .HasForeignKey("ScheduledExecutionId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledExecution");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledExecutions", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.TripVaults", "TripVault")
                        .WithMany()
                        .HasForeignKey("TripVaultId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripVault");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledFlightQueries", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Airports", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Airports", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.ScheduledExecutions", "ScheduledExecution")
                        .WithMany()
                        .HasForeignKey("ScheduledExecutionId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartureAirport");

                    b.Navigation("DestinationAirport");

                    b.Navigation("ScheduledExecution");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledHotelQueries", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ScheduledExecutions", "ScheduledExecution")
                        .WithMany()
                        .HasForeignKey("ScheduledExecutionId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledExecution");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledLocalPlacesQueries", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ScheduledExecutions", "ScheduledExecution")
                        .WithMany()
                        .HasForeignKey("ScheduledExecutionId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledExecution");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ScheduledWeatherQueries", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ScheduledExecutions", "ScheduledExecution")
                        .WithMany()
                        .HasForeignKey("ScheduledExecutionId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledExecution");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.ServiceTokenCosts", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ServiceTypes", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.TripQueryHistories", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.ServiceTypes", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.TripVaults", "TripVault")
                        .WithMany()
                        .HasForeignKey("TripVaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("TripVault");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.TripVaults", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Users", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserMonthlyTokenCounts", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserPreferences", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.PreferenceTypes", "PreferenceTypes")
                        .WithMany("UserPreferences")
                        .HasForeignKey("PreferenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripRadar.Server.Db.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferenceTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserProfiles", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Countries", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("TripRadar.Server.Db.Models.Languages", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.UserSubscriptions", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.Tiers", "PendingTier")
                        .WithMany()
                        .HasForeignKey("PendingTierId");

                    b.HasOne("TripRadar.Server.Db.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingTier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.Users", b =>
                {
                    b.HasOne("TripRadar.Server.Db.Models.PromoCodes", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("TripRadar.Server.Db.Models.Tiers", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.FeedbackCategories", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("TripRadar.Server.Db.Models.PreferenceTypes", b =>
                {
                    b.Navigation("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
