using System.Text.Json.Serialization;
using DigitalBrain.Abstractions.Commands;
using DigitalBrain.Abstractions.Descriptors;
using DigitalBrain.Coding;

[assembly: NeuronJsonContext(typeof(CodingJson))]

namespace DigitalBrain.Coding;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
[JsonSerializable(typeof(OpenWorkspace))]
[JsonSerializable(typeof(ReloadWorkspace))]
[JsonSerializable(typeof(WorkspaceReceipt))]
[JsonSerializable(typeof(Accepted<WorkspaceReceipt>))]
[JsonSerializable(typeof(OpeningBody))]
[JsonSerializable(typeof(MappingBody))]
[JsonSerializable(typeof(WorkspacePhase))]
[JsonSerializable(typeof(WorkspaceSnapshot))]
[JsonSerializable(typeof(SymbolSearch))]
[JsonSerializable(typeof(SymbolHit))]
[JsonSerializable(typeof(SymbolSearchResult))]
[JsonSerializable(typeof(ReferenceSearch))]
[JsonSerializable(typeof(ReferenceHit))]
[JsonSerializable(typeof(ReferenceSearchResult))]
[JsonSerializable(typeof(DiagnosticsQuery))]
[JsonSerializable(typeof(DiagnosticHit))]
[JsonSerializable(typeof(DiagnosticsResult))]
[JsonSerializable(typeof(MapQuery))]
[JsonSerializable(typeof(ProjectNode))]
[JsonSerializable(typeof(ProjectEdge))]
[JsonSerializable(typeof(SolutionMap))]
[JsonSerializable(typeof(EditKind))]
[JsonSerializable(typeof(EditRequest))]
[JsonSerializable(typeof(ProposeEdit))]
[JsonSerializable(typeof(CheckChangeSet))]
[JsonSerializable(typeof(CommitChangeSet))]
[JsonSerializable(typeof(DiscardChangeSet))]
[JsonSerializable(typeof(ChangeSetReceipt))]
[JsonSerializable(typeof(Accepted<ChangeSetReceipt>))]
[JsonSerializable(typeof(ChangeSetStatus))]
[JsonSerializable(typeof(ChangeSetSnapshot))]
[JsonSerializable(typeof(CommittingBody))]
[JsonSerializable(typeof(SkeletonQuery))]
[JsonSerializable(typeof(SkeletonMember))]
[JsonSerializable(typeof(Skeleton))]
[JsonSerializable(typeof(MemberQuery))]
[JsonSerializable(typeof(MemberSource))]
[JsonSerializable(typeof(CallersQuery))]
[JsonSerializable(typeof(CallerHit))]
[JsonSerializable(typeof(CallersResult))]
[JsonSerializable(typeof(ImplementationsQuery))]
[JsonSerializable(typeof(DerivedQuery))]
[JsonSerializable(typeof(BuildSlot))]
[JsonSerializable(typeof(PromoteSlot))]
[JsonSerializable(typeof(RetireSlot))]
[JsonSerializable(typeof(SlotReceipt))]
[JsonSerializable(typeof(Accepted<SlotReceipt>))]
[JsonSerializable(typeof(SlotPhase))]
[JsonSerializable(typeof(SlotSnapshot))]
[JsonSerializable(typeof(SlotBuildingBody))]
[JsonSerializable(typeof(SlotPromotionBody))]
public sealed partial class CodingJson : JsonSerializerContext;
