<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>GitHub neuron contracts.</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>DigitalBrain.Microsoft.GitHub</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../DigitalBrain/Kernel/Contracts/DigitalBrain.Contracts.csproj" />
  </ItemGroup>
</Project>
