<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>a25ed5bb-db99-4b94-afbe-79ce2e560b7d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
