<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IntoChat.Tests.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../../IntoChat/IntoChat.csproj" />
    <ProjectReference Include="../../../../Modules/DigitalBrain/Kernel/DigitalBrain.Kernel.Aspire.Hosting/DigitalBrain.Kernel.Aspire.Hosting.csproj" />
    <ProjectReference Include="../../../../Modules/DigitalBrain/Compute/DigitalBrain.Modules.Compute/DigitalBrain.Modules.Compute.csproj" />
    <ProjectReference Include="../../../../Modules/DigitalBrain/Mcp/DigitalBrain.Mcp.csproj" />
  </ItemGroup>
</Project>

