using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DigitalBrain.SourceGen;

// Discovers every non-abstract type deriving from (or equal to) DigitalBrain.Core.Synapse reachable
// from the compiling project and emits DigitalBrain.Kernel.JournalJsonContext, replacing a
// hand-maintained per-type [JsonSerializable] list that already caused one real bug (a missed
// Synapse subtype) with a build-time guarantee.
//
// Why this emits a full JsonSerializerContext body instead of just [JsonSerializable] attributes for
// System.Text.Json's own bundled generator to process (the more obvious design): verified empirically
// that it doesn't work. Roslyn source generators never see another generator's AddSource output within
// the same compile pass (only Compilation.CompilationProvider's *original*, pre-generator syntax is
// visible to every generator's RegisterSourceOutput callback) - so System.Text.Json's generator, looking
// for [JsonSerializable]-decorated partial JsonSerializerContext declarations in the original source,
// never finds ones added by this generator. Confirmed by building with EmitCompilerGeneratedFiles=true:
// only this generator's own output appeared; System.Text.Json.SourceGeneration produced nothing for
// JournalJsonContext, leaving its two abstract members (GeneratedSerializerOptions, GetTypeInfo)
// unimplemented (CS0534). RegisterPreCompilationSourceOutput - the newer Roslyn API built for exactly
// this "make my output visible to other generators" case - explicitly forbids depending on the
// Compilation, which this generator's whole job requires. So this type implements JsonSerializerContext
// directly: the discovered-type LIST stays fully source-generated and missing-type-proof (that's the
// actual bug this task fixes), while per-type JsonTypeInfo construction delegates to
// DefaultJsonTypeInfoResolver (reflection) instead of System.Text.Json's source-generated codecs. Orleans
// Journaling's JSON codec only refuses to run when a TypeInfoResolver is entirely unconfigured, not when
// GetTypeInfo happens to be reflection-backed - see Orleans.Journaling README.
[Generator]
public sealed class SynapseJsonContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var synapseTypeNames = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var synapseBase = compilation.GetTypeByMetadataName("DigitalBrain.Core.Synapse");
            if (synapseBase is null)
                return ImmutableArray<string>.Empty;

            return CollectCandidateTypes(compilation)
                // Public only: a discovered internal/private type would be inaccessible from the
                // JournalJsonContext.g.cs emitted into DigitalBrain.Kernel, breaking Kernel's build
                // (CS0122) rather than just being harmlessly excluded.
                .Where(type => !type.IsAbstract
                    && type.DeclaredAccessibility == Accessibility.Public
                    && IsSynapseOrDerivedFromSynapse(type, synapseBase))
                .Select(static t => t.ToDisplayString())
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static name => name, StringComparer.Ordinal)
                .ToImmutableArray();
        });

        context.RegisterSourceOutput(synapseTypeNames, static (spc, names) =>
            spc.AddSource("JournalJsonContext.g.cs", EmitJournalJsonContext(names)));
    }

    private static string EmitJournalJsonContext(ImmutableArray<string> displayNames)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated by DigitalBrain.SourceGen.SynapseJsonContextGenerator />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.Text.Json;");
        source.AppendLine("using System.Text.Json.Serialization;");
        source.AppendLine("using System.Text.Json.Serialization.Metadata;");
        source.AppendLine();
        source.AppendLine("namespace DigitalBrain.Kernel;");
        source.AppendLine();
        source.AppendLine("public partial class JournalJsonContext : JsonSerializerContext");
        source.AppendLine("{");

        source.AppendLine("    private static readonly HashSet<Type> KnownSynapseTypes = new()");
        source.AppendLine("    {");
        source.AppendLine(string.Join("\n", displayNames.Select(static name => $"        typeof({name}),")));
        source.AppendLine("    };");
        source.AppendLine();

        // Deliberately separate from Options (below): Options.TypeInfoResolver is `this`, so resolving
        // through Options for nested property types (e.g. NeuronId inside Synapse) would loop back into
        // this type's own gated GetTypeInfo. ReflectionOptions is un-gated, self-contained, and derived
        // per-instance from Options so a caller-supplied naming policy / converters are still honored
        // instead of silently ignored (this context isn't only ever used via Default).
        source.AppendLine("    private JsonSerializerOptions? _reflectionOptions;");
        source.AppendLine("    private JsonSerializerOptions ReflectionOptions =>");
        source.AppendLine("        _reflectionOptions ??= new JsonSerializerOptions(Options) { TypeInfoResolver = new DefaultJsonTypeInfoResolver() };");
        source.AppendLine();
        source.AppendLine("    private static readonly JsonSerializerOptions DefaultOptions = new();");
        source.AppendLine();
        source.AppendLine("    public static JournalJsonContext Default { get; } = new(new JsonSerializerOptions(DefaultOptions));");
        source.AppendLine();
        // Every construction path gets its own fresh JsonSerializerOptions instance - a JsonSerializerOptions
        // can only ever be bound to one JsonSerializerContext, so two contexts must never share the same
        // DefaultOptions reference (which a plain `base(null)` relying on GeneratedSerializerOptions would do).
        source.AppendLine("    public JournalJsonContext() : base(new JsonSerializerOptions(DefaultOptions)) { }");
        source.AppendLine();
        source.AppendLine("    public JournalJsonContext(JsonSerializerOptions? options) : base(options ?? new JsonSerializerOptions(DefaultOptions)) { }");
        source.AppendLine();
        source.AppendLine("    protected override JsonSerializerOptions? GeneratedSerializerOptions { get; } = DefaultOptions;");
        source.AppendLine();
        source.AppendLine("    public override JsonTypeInfo? GetTypeInfo(Type type) =>");
        source.AppendLine("        KnownSynapseTypes.Contains(type) && ReflectionOptions.TryGetTypeInfo(type, out var typeInfo) ? typeInfo : null;");
        source.AppendLine();

        source.AppendLine(string.Join("\n\n", displayNames.Select(static name =>
        {
            var propertyName = name.Substring(name.LastIndexOf('.') + 1);
            return $"    public JsonTypeInfo<{name}> {propertyName} => (JsonTypeInfo<{name}>)(GetTypeInfo(typeof({name}))!);";
        })));

        source.AppendLine("}");
        return source.ToString();
    }

    // Compilation.GetSymbolsWithName only walks this compilation's own SourceModule - it never sees
    // types from referenced assemblies. Most Synapse subtypes live in DigitalBrain.Core, a referenced
    // project, so that API alone would silently miss almost everything (verified empirically: it finds
    // a Synapse subtype declared inline in a test compilation, but not ones compiled into a referenced
    // DigitalBrain.Core.dll). Walk this compilation's own source plus every referenced assembly whose
    // name starts with "DigitalBrain" - every Synapse subtype in this codebase lives in a DigitalBrain.*
    // project; skipping BCL/Orleans/gRPC/Azure/etc. references keeps this from becoming a full transitive
    // symbol-table walk (tens of thousands of types) on every keystroke.
    private static IEnumerable<INamedTypeSymbol> CollectCandidateTypes(Compilation compilation)
    {
        foreach (var type in GetAllNamedTypes(compilation.Assembly.GlobalNamespace))
            yield return type;

        foreach (var referencedAssembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (!referencedAssembly.Name.StartsWith("DigitalBrain", StringComparison.Ordinal))
                continue;

            foreach (var type in GetAllNamedTypes(referencedAssembly.GlobalNamespace))
                yield return type;
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllNamedTypes(INamespaceSymbol root)
    {
        var pending = new Stack<INamespaceOrTypeSymbol>();
        pending.Push(root);

        while (pending.Count > 0)
        {
            var current = pending.Pop();
            foreach (var member in current.GetMembers())
            {
                switch (member)
                {
                    case INamespaceSymbol nestedNamespace:
                        pending.Push(nestedNamespace);
                        break;
                    case INamedTypeSymbol namedType:
                        yield return namedType;
                        pending.Push(namedType); // nested types
                        break;
                }
            }
        }
    }

    private static bool IsSynapseOrDerivedFromSynapse(INamedTypeSymbol type, INamedTypeSymbol synapseBase)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, synapseBase))
                return true;
        }
        return false;
    }
}
