<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DigitalBrain</RootNamespace>
    <NoWarn>$(NoWarn);ORLEANSEXP005;CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalBrain.Core\DigitalBrain.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" />
  </ItemGroup>
</Project>
