<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TripRadar.Server.Domain\TripRadar.Server.Domain.csproj"/>
    <ProjectReference Include="..\TripRadar.Server.Comms.Core\TripRadar.Server.Comms.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper"/>
    <PackageReference Include="BCrypt.Net-Next"/>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Microsoft.AspNetCore.Http"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\SearchEngine\" />
  </ItemGroup>

</Project>
