<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
    <ProjectReference Include="../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../../DigitalBrain.Aspire.Server/DigitalBrain.Aspire.Server.csproj" />
    <ProjectReference Include="../../DigitalBrain.Aspire.Client/DigitalBrain.Aspire.Client.csproj" />
    <None Update="Fixtures/*.cs.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
