<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>DigitalBrain.Mcp</RootNamespace>
    <NoWarn>$(NoWarn);CA2007;CA1812</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Modules/UI/DigitalBrain.Modules.UI.Contracts/DigitalBrain.Modules.UI.Contracts.csproj" />
    <ProjectReference Include="../../Aspire/DigitalBrain.Aspire/DigitalBrain.Aspire.csproj" />
    <ProjectReference Include="../DigitalBrain.Client/DigitalBrain.Client.csproj" />
  </ItemGroup>
</Project>
