<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../../Testing/Integration.Tests.props" />
  <PropertyGroup>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../Google/DigitalBrain.Modules.Google.csproj" />
    <ProjectReference Include="../../Aspire.Hosting/DigitalBrain.Modules.Google.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
