<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DigitalBrain.Aspire" Version="$(DigitalBrainVersion)" />
    <PackageVersion Include="DigitalBrain.Aspire.Hosting" Version="$(DigitalBrainVersion)" />
    <PackageVersion Include="DigitalBrain.DevTools" Version="$(DigitalBrainVersion)" />
    <PackageVersion Include="DigitalBrain.Kernel" Version="$(DigitalBrainVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>
</Project>
