<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Accounts, members, roles, principals and grants.</Description>
    <RootNamespace>DigitalBrain.Identity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DigitalBrain.Modules.Identity.Tests.Unit" />
    <ProjectReference Include="../Contracts/DigitalBrain.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="../../DigitalBrain/Kernel/Kernel/DigitalBrain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
