<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Aspire/Brain.Aspire/Brain.Aspire.csproj" />
    <ProjectReference Include="../Brain.Product.Abstractions/Brain.Product.Abstractions.csproj" />
    <ProjectReference Include="../Brain.Core/Brain.Core.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' != 'Debug'">
    <Compile Remove="Authority/LocalTestAuthority.cs" />
  </ItemGroup>
</Project>
