<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Greeter</RootNamespace>
    <AssemblyName>Greeter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Greeter.Contracts\Greeter.Contracts.csproj" />
  </ItemGroup>

</Project>
