<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Resources\Localization\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="..\TripRadar.Localization\flight-translations.json" Link="Resources\flight-translations.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TripRadar.Server.Application\TripRadar.Server.Application.csproj"/>
    <ProjectReference Include="..\TripRadar.Server.Db\TripRadar.Server.Db.csproj"/>
    <ProjectReference Include="..\TripRadar.Server.Domain\TripRadar.Server.Domain.csproj"/>
    <ProjectReference Include="..\TripRadar.Server.Mocks\TripRadar.Server.Mocks.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka"/>
    <PackageReference Include="Cronos"/>
    <PackageReference Include="BCrypt.Net-Next"/>
    <PackageReference Include="Azure.Communication.Email"/>
    <PackageReference Include="google-search-results-dotnet"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis"/>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder"/>
    <PackageReference Include="NodaTime"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Npgsql"/>
    <PackageReference Include="Polly"/>
    <PackageReference Include="Hangfire.PostgreSql"/>
    <PackageReference Include="Hangfire.AspNetCore"/>
    <PackageReference Include="Hangfire.MemoryStorage"/>
    <PackageReference Include="Stripe.net"/>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
    <PackageReference Include="Microsoft.Extensions.Options"/>
    <PackageReference Include="Newtonsoft.Json"/>
    <PackageReference Include="Azure.Identity"/>
  </ItemGroup>

</Project>

