<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Ino.Core\Ino.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Ino.Core.Hosting\Ino.Core.Hosting.csproj" />
  </ItemGroup>
</Project>
