// LF-only RFW source for the DigitalBrain agent swarm control center.
// Per the PR #71 CRLF guard, built with explicit '\n' concatenation so
// the constant is byte-stable regardless of git autocrlf behavior.
const String kTaskManagerCardSource =
    'import digitalbrain;\n'
    '\n'
    'widget TaskManagerCard = VStack(\n'
    '  gap: 14.0,\n'
    '  children: [\n'
    '    Panel(\n'
    '      radius: 24.0,\n'
    '      padding: 22.0,\n'
    '      child: VStack(\n'
    '        gap: 18.0,\n'
    '        cross: "start",\n'
    '        children: [\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              VStack(\n'
    '                gap: 5.0,\n'
    '                cross: "start",\n'
    '                children: [\n'
    '                  SectionLabel(text: "AGENT SWARM / LIVE"),\n'
    '                  Text(text: "Control Center", variant: "heading"),\n'
    '                  Text(text: "Orchestrated executions projected from live synapses.", variant: "dim"),\n'
    '                ],\n'
    '              ),\n'
    '              Badge(text: "RFW LIVE", tone: "teal"),\n'
    '            ],\n'
    '          ),\n'
    '          Divider(),\n'
    '          HStack(\n'
    '            gap: 10.0,\n'
    '            children: [\n'
    '              Counter(value: data.totals.active, tone: "indigo", label: "running"),\n'
    '              Counter(value: data.totals.completed, tone: "teal", label: "settled"),\n'
    '              Counter(value: data.totals.failed, tone: "rose", label: "failed"),\n'
    '            ],\n'
    '          ),\n'
    '        ],\n'
    '      ),\n'
    '    ),\n'
    '    Panel(\n'
    '      radius: 20.0,\n'
    '      padding: 18.0,\n'
    '      child: VStack(\n'
    '        gap: 12.0,\n'
    '        cross: "stretch",\n'
    '        children: [\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              SectionLabel(text: "ACTIVE EXECUTIONS"),\n'
    '              Text(text: "CORRELATION / LATENCY / EDGES", variant: "mono"),\n'
    '            ],\n'
    '          ),\n'
    '          ...for task in data.tasks:\n'
    '            TaskRow(\n'
    '              correlationId: task.correlationId,\n'
    '              shortHash: task.shortHash,\n'
    '              originNeuron: task.originNeuron,\n'
    '              originIcon: task.originIcon,\n'
    '              ageMs: task.ageMs,\n'
    '              edgeCount: task.edgeCount,\n'
    '              status: task.status,\n'
    '              onCancel: event "cancelTask" { correlationId: task.correlationId },\n'
    '            ),\n'
    '        ],\n'
    '  ],\n'
    ');\n';

const String kNemoChatCardSource =
    'import digitalbrain;\n'
    '\n'
    'widget NemoChatCard = VStack(\n'
    '  gap: 14.0,\n'
    '  children: [\n'
    '    Panel(\n'
    '      radius: 24.0,\n'
    '      padding: 22.0,\n'
    '      child: VStack(\n'
    '        gap: 18.0,\n'
    '        cross: "start",\n'
    '        children: [\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              VStack(\n'
    '                gap: 5.0,\n'
    '                cross: "start",\n'
    '                children: [\n'
    '                  SectionLabel(text: "LOCAL COGNITIVE NEURON"),\n'
    '                  Text(text: "Nemo LLM Integration", variant: "heading"),\n'
    '                  Text(text: "Real-time responses back from the local nemotron-mini model.", variant: "dim"),\n'
    '                ],\n'
    '              ),\n'
    '              Badge(text: "NEMO-MINI", tone: "violet"),\n'
    '            ],\n'
    '          ),\n'
    '          Divider(),\n'
    '          VStack(\n'
    '            gap: 12.0,\n'
    '            cross: "start",\n'
    '            children: [\n'
    '              Text(text: "USER PROMPT:", variant: "label"),\n'
    '              Text(text: data.prompt, variant: "body"),\n'
    '            ],\n'
    '          ),\n'
    '        ],\n'
    '      ),\n'
    '    ),\n'
    '    Panel(\n'
    '      radius: 24.0,\n'
    '      padding: 22.0,\n'
    '      child: VStack(\n'
    '        gap: 14.0,\n'
    '        cross: "start",\n'
    '        children: [\n'
    '          Text(text: "RESPONSE:", variant: "label"),\n'
    '          Text(text: data.response, variant: "body"),\n'
    '        ],\n'
    '      ),\n'
    '    ),\n'
    '    Panel(\n'
    '      radius: 20.0,\n'
    '      padding: 18.0,\n'
    '      child: VStack(\n'
    '        gap: 12.0,\n'
    '        cross: "stretch",\n'
    '        children: [\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              SectionLabel(text: "GENAI COGNITIVE TELEMETRY"),\n'
    '              Text(text: "HARDWARE / VRAM / INFERENCE", variant: "mono"),\n'
    '            ],\n'
    '          ),\n'
    '          Divider(),\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              Text(text: "Provider", variant: "dim"),\n'
    '              Badge(text: data.telemetry.provider, tone: "indigo"),\n'
    '            ],\n'
    '          ),\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              Text(text: "Model", variant: "dim"),\n'
    '              Badge(text: data.telemetry.model, tone: "violet"),\n'
    '            ],\n'
    '          ),\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              Text(text: "Input Tokens", variant: "dim"),\n'
    '              Counter(value: data.telemetry.inputTokens, tone: "indigo", label: "tokens"),\n'
    '            ],\n'
    '          ),\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              Text(text: "Output Tokens", variant: "dim"),\n'
    '              Counter(value: data.telemetry.outputTokens, tone: "teal", label: "tokens"),\n'
    '            ],\n'
    '          ),\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              Text(text: "Inference Time", variant: "dim"),\n'
    '              Badge(text: data.telemetry.duration, tone: "gold"),\n'
    '            ],\n'
    '          ),\n'
    '          HStack(\n'
    '            between: true,\n'
    '            children: [\n'
    '              Text(text: "Generation Speed", variant: "dim"),\n'
    '              Badge(text: data.telemetry.speed, tone: "teal"),\n'
    '            ],\n'
    '          ),\n'
    '        ],\n'
    '      ),\n'
    '    ),\n'
    '  ],\n'
    ');\n';

Map<String, dynamic> cleanRfwData(Map<String, dynamic> data) {
  final Map<String, dynamic> result = {};
  data.forEach((k, v) {
    if (v != null) {
      result[k] = _cleanValue(v);
    }
  });
  return result;
}

Object? _cleanValue(Object? value) {
  if (value is Map) {
    final Map<String, dynamic> result = {};
    value.forEach((k, v) {
      if (v != null) {
        result[k.toString()] = _cleanValue(v);
      }
    });
    return result;
  } else if (value is List) {
    final List<Object?> result = [];
    for (final item in value) {
      if (item != null) {
        result.add(_cleanValue(item));
      }
    }
    return result;
  }
  return value;
}

