<Project Sdk="Aspire.AppHost.Sdk/13.5.0-preview.1.26376.5">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UserSecretsId>digitalbrain-corev2-apphost-5d79b5c8-c54e-4f65-895f-e7e3b8a709b4</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Aspire/Brain.Aspire.Hosting/Brain.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../Modules/AI/Aspire.Hosting/Brain.Modules.AI.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../Modules/AI/Contracts/Brain.Modules.AI.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../Modules/UI/Aspire.Hosting/Brain.Modules.UI.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../Modules/UI/Runtime/Brain.Modules.UI.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../DigitalBrain.ProductHost/DigitalBrain.ProductHost.csproj" />
    <ProjectReference Include="../DigitalBrain.RuntimeHost/DigitalBrain.RuntimeHost.csproj" />
  </ItemGroup>
</Project>
