<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>DigitalBrain.Sdk.Tests.Unit</RootNamespace></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <ProjectReference Include="../../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../DigitalBrain.Sdk/DigitalBrain.Sdk.csproj" />
    <None Update="Identity/LegacyState/*.orleans" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup><EmbeddedResource Include="Types/TypeCatalog.v0.json" /></ItemGroup>
</Project>
