<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.BotAPI" />
    <PackageReference Include="Aspire.Confluent.Kafka" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Yarp.ReverseProxy" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TripRadar.ServiceDefaults\TripRadar.ServiceDefaults.csproj" />
    <ProjectReference Include="..\TripRadar.MiniApp\TripRadar.MiniApp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TripRadar.Bot.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
