<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Microsoft GitHub and Aspire integration.</Description>
    <RootNamespace>DigitalBrain.Microsoft</RootNamespace>
    <NoWarn>$(NoWarn);ORLEANSEXP005</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="Octokit.Webhooks" />
    <PackageReference Include="ModelContextProtocol.Core" />
    <ProjectReference Include="../Contracts/DigitalBrain.Modules.Microsoft.Contracts.csproj" />
    <ProjectReference Include="../../AI/Contracts/DigitalBrain.Modules.AI.Contracts.csproj" />
    <ProjectReference Include="../../../Kernel/DigitalBrain/DigitalBrain.csproj" />
    <InternalsVisibleTo Include="DigitalBrain.Tests" />
  </ItemGroup>
</Project>
