<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Microsoft GitHub and Aspire integration.</Description>
    <RootNamespace>DigitalBrain.Microsoft</RootNamespace>
    <NoWarn>$(NoWarn);ORLEANSEXP005</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DigitalBrain.Modules.Microsoft.Tests.Unit" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Contracts/DigitalBrain.Modules.Microsoft.Contracts.csproj" />
    <ProjectReference Include="../../DigitalBrain/DigitalBrain/DigitalBrain.csproj" />
    <ProjectReference Include="../../DigitalBrain/Sdk/DigitalBrain.Sdk.csproj" />
  </ItemGroup>
</Project>