<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../../DigitalBrain.Modules.Salesforce/DigitalBrain.Modules.Salesforce.csproj" />
    <ProjectReference Include="../../../../DigitalBrain/Platform/DigitalBrain.Platform/DigitalBrain.Platform.csproj" />
  </ItemGroup>
</Project>
