name: Auto-add issues to projects by label

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-miniapp:
    if: contains(github.event.issue.labels.*.name, 'area: miniapp')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/RoseXTechnology/projects/6
          github-token: ${{ secrets.PROJECT_TOKEN }}

  add-to-server:
    if: contains(github.event.issue.labels.*.name, 'area: server')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/RoseXTechnology/projects/7
          github-token: ${{ secrets.PROJECT_TOKEN }}

  add-to-website:
    if: contains(github.event.issue.labels.*.name, 'area: website')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/RoseXTechnology/projects/8
          github-token: ${{ secrets.PROJECT_TOKEN }}

  add-to-companion-ai:
    if: contains(github.event.issue.labels.*.name, 'area: agents')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/RoseXTechnology/projects/9
          github-token: ${{ secrets.PROJECT_TOKEN }}

  add-to-miniapp-from-bot:
    if: contains(github.event.issue.labels.*.name, 'area: telegram bot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/RoseXTechnology/projects/6
          github-token: ${{ secrets.PROJECT_TOKEN }}
