<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>GitHub repository and connection neurons.</Description>
    <RootNamespace>DigitalBrain.Microsoft.GitHub</RootNamespace>
    <NoWarn>$(NoWarn);ORLEANSEXP005</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DigitalBrain.Modules.Microsoft.GitHub.Tests.Unit" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Contracts/DigitalBrain.Modules.Microsoft.GitHub.Contracts.csproj" />
    <ProjectReference Include="../../../DigitalBrain/DigitalBrain/DigitalBrain.csproj" />
    <ProjectReference Include="../../../DigitalBrain/Sdk/DigitalBrain.Sdk.csproj" />
  </ItemGroup>
</Project>
