<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="DigitalBrain.Testing" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <ProjectReference Include="../DigitalBrain/DigitalBrain.csproj" />
  </ItemGroup>
</Project>
