// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DigitalBrain.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PackConfigFormOnInstallSlice2_Config_DrivenExperienceFeature : object, global::Xunit.IClassFixture<PackConfigFormOnInstallSlice2_Config_DrivenExperienceFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Pack config form on install (Slice 2 - config-driven experience)", "\tAs a user installing a pack that declares RequiredConfig\r\n\tI want the kernel to " +
                "render an in-app config form on install\r\n\tSo that submitting it persists my valu" +
                "es (encrypted) without leaving the app", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TelegramExperience.feature"
#line hidden
        
        public PackConfigFormOnInstallSlice2_Config_DrivenExperienceFeature(PackConfigFormOnInstallSlice2_Config_DrivenExperienceFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/TelegramExperience.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Installing a pack with RequiredConfig emits a config form and submit persists val" +
            "ues")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pack config form on install (Slice 2 - config-driven experience)")]
        [global::Xunit.TraitAttribute("Description", "Installing a pack with RequiredConfig emits a config form and submit persists val" +
            "ues")]
        [global::Xunit.TraitAttribute("Category", "distribution")]
        [global::Xunit.TraitAttribute("Category", "config")]
        public async global::System.Threading.Tasks.Task InstallingAPackWithRequiredConfigEmitsAConfigFormAndSubmitPersistsValues()
        {
            string[] tagsOfScenario = new string[] {
                    "distribution",
                    "config"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Installing a pack with RequiredConfig emits a config form and submit persists val" +
                    "ues", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await testRunner.GivenAsync("a generic pack \"GenericConfiguredPack\" declaring 3 required config fields", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
  await testRunner.WhenAsync("I publish and install the pack", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
  await testRunner.ThenAsync("a config form surface is emitted whose tree contains the fields \"telegram_token\"," +
                        " \"llm_provider\", \"llm_key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
  await testRunner.WhenAsync("I submit configuration for the pack with token \"tok-123\", provider \"openai\", key " +
                        "\"sk-secret\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
  await testRunner.ThenAsync("the pack config store returns token \"tok-123\", provider \"openai\", key \"sk-secret\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Full reactive loop - an inbound message round-trips through the pack and the stub" +
            "bed LLM to an egress reply")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pack config form on install (Slice 2 - config-driven experience)")]
        [global::Xunit.TraitAttribute("Description", "Full reactive loop - an inbound message round-trips through the pack and the stub" +
            "bed LLM to an egress reply")]
        [global::Xunit.TraitAttribute("Category", "distribution")]
        [global::Xunit.TraitAttribute("Category", "e2e")]
        public async global::System.Threading.Tasks.Task FullReactiveLoop_AnInboundMessageRound_TripsThroughThePackAndTheStubbedLLMToAnEgressReply()
        {
            string[] tagsOfScenario = new string[] {
                    "distribution",
                    "e2e"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Full reactive loop - an inbound message round-trips through the pack and the stub" +
                    "bed LLM to an egress reply", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await testRunner.GivenAsync("the Telegram responder experience is installed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
  await testRunner.ThenAsync("the install emits a config form whose tree contains the fields \"telegram_token\", " +
                        "\"llm_provider\", \"llm_key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
  await testRunner.WhenAsync("I provide the Telegram configuration token \"tok-123\", provider \"openai\", key \"sk-" +
                        "secret\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.AndAsync("the LLM responder is active and the egress bus is watching \"TelegramReplyRequeste" +
                        "d\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.AndAsync("a Telegram message arrives for chat 7 with text \"hi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.ThenAsync("the embodied pack emits an AskLlm for \"hi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
  await testRunner.AndAsync("a \"TelegramReplyRequested\" reply for chat 7 with text \"ANSWER:hi\" reaches the egr" +
                        "ess bus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="N+1 reactivity - two packs both react to one broadcast with no restart")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pack config form on install (Slice 2 - config-driven experience)")]
        [global::Xunit.TraitAttribute("Description", "N+1 reactivity - two packs both react to one broadcast with no restart")]
        [global::Xunit.TraitAttribute("Category", "distribution")]
        [global::Xunit.TraitAttribute("Category", "e2e")]
        [global::Xunit.TraitAttribute("Category", "n1")]
        public async global::System.Threading.Tasks.Task N1Reactivity_TwoPacksBothReactToOneBroadcastWithNoRestart()
        {
            string[] tagsOfScenario = new string[] {
                    "distribution",
                    "e2e",
                    "n1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("N+1 reactivity - two packs both react to one broadcast with no restart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
  await testRunner.GivenAsync("both the Telegram responder and the keyword watcher are installed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
  await testRunner.AndAsync("I provide the Telegram configuration token \"tok-123\", provider \"openai\", key \"sk-" +
                        "secret\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
  await testRunner.AndAsync("the LLM responder is active and the egress bus is watching \"TelegramReplyRequeste" +
                        "d\" and \"ReminderScheduled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.WhenAsync("a Telegram message with text \"remind me to call mom\" is ingested for chat 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
  await testRunner.ThenAsync("a \"TelegramReplyRequested\" reply for chat 7 reaches the egress bus", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
  await testRunner.AndAsync("a \"ReminderScheduled\" signal for chat 7 reaches the egress bus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PackConfigFormOnInstallSlice2_Config_DrivenExperienceFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PackConfigFormOnInstallSlice2_Config_DrivenExperienceFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
