<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Data.Tables" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\core\behaviors\DigitalBrain.Behaviors.Host\DigitalBrain.Behaviors.Host.csproj" />
    <ProjectReference Include="..\..\src\core\aspire\DigitalBrain.Aspire\DigitalBrain.Aspire.csproj" />
    <ProjectReference Include="..\..\src\core\aspire\DigitalBrain.ServiceDefaults\DigitalBrain.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\src\core\security\DigitalBrain.Security\DigitalBrain.Security.csproj" />
  </ItemGroup>
</Project>
