<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TripRadar.DeploymentKit\TripRadar.DeploymentKit.csproj" />
    <ProjectReference Include="..\TripRadar.Server.Comms.Core\TripRadar.Server.Comms.Core.csproj"/>
    <ProjectReference Include="..\TripRadar.Server.Db\TripRadar.Server.Db.csproj" />
    <PackageReference Include="Npgsql"/>
  </ItemGroup>

</Project>
