<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Aspire/Brain.Aspire/Brain.Aspire.csproj" />
    <ProjectReference Include="../Brain.Core/Brain.Core.csproj" />
    <ProjectReference Include="../Modules/AI/Runtime/Brain.Modules.AI.csproj" />
    <ProjectReference Include="../Modules/Proof/Runtime/Brain.Modules.Proof.csproj" />
    <ProjectReference Include="../Modules/UI/Runtime/Brain.Modules.UI.csproj" />
  </ItemGroup>
</Project>
