<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../kernel/Brain.Client/Brain.Client.csproj" />
    <ProjectReference Include="../../modules/Brain.Modules.Workspace/Brain.Modules.Workspace.csproj" />
    <ProjectReference Include="../../modules/Brain.Modules.Ai/Brain.Modules.Ai.csproj" />
  </ItemGroup>
</Project>
