<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>DigitalBrain.Microsoft.Playwright</RootNamespace><NoWarn>$(NoWarn);CS1591</NoWarn></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../DigitalBrain/Kernel/DigitalBrain.Contracts/DigitalBrain.Contracts.csproj" /></ItemGroup>
</Project>
