<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../Testing/Module.Tests.props" />
  <ItemGroup>
    <ProjectReference Include="../DigitalBrain/DigitalBrain.csproj" />
    <ProjectReference Include="../../../Behaviors/ElonBitcoin.csproj" />
    <ProjectReference Include="../../../Behaviors/InvoiceFollowUp.csproj" />
    <ProjectReference Include="../../../Behaviors/MondayInvoices.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <PackageReference Include="Microsoft.Orleans.BroadcastChannel" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="BehaviorMailboxFacts.cs" />
    <Compile Remove="BrainSimulationFacts.cs" />
    <Compile Remove="ModuleEndpointFacts.cs" />
    <Compile Remove="ScenarioFacts.cs" />
  </ItemGroup>
</Project>
