export const ROUTES = {
  HOME: '/',
  PRICING: '/pricing',
  CHANGELOG: '/changelog',
  HELP: '/help',
  LOGIN: '/signin',
  SIGNUP: '/signup',
  FEEDBACK: '/feedback',
  UNSUBSCRIBE: '/unsubscribe',
  GUIDE_TELEGRAM_PLANNER: '/telegram-trip-planner',
  GUIDE_BUDGET_AI_PLANNER: '/ai-trip-planner-budget',
  GUIDE_ALTERNATIVES: '/trip-planning-assistant-alternatives',
  GUIDE_BUDGET_GUIDE_2026: '/trip-budget-guide-2026',
  GUIDE_CHECKLIST_TEMPLATE: '/trip-checklist-template',
  GUIDE_MANUAL_VS_TRIPRADAR: '/manual-planning-vs-tripradar',
  GUIDE_EXAMPLE_PLAN: '/example-trip-plan',
  GUIDE_SAVINGS_METHODOLOGY: '/savings-methodology',
  EMAIL_SENT: '/email-sent',
  EMAIL_CONFIRMATION: '/confirm-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  TELEGRAM_CALLBACK: '/auth/telegram-callback',
  TELEGRAM_USERNAME_SYNC: '/auth/telegram-username-sync',
  PROFILE: '/profile',
  PROFILE_BILLING: '/profile/billing',
  PROFILE_USAGE: '/profile/usage',
  PROFILE_SCHEDULED_REQUESTS: '/profile/scheduled-requests',
  PROFILE_TRIPS: '/profile/trips',
  PROFILE_TRIP_HISTORY: '/profile/trips/:tripUniqueId/history',
  SUBSCRIPTION_CHECKOUT: '/subscription/checkout',
  SUBSCRIPTION_SUCCESS: '/subscription/success',
  COOKIES: '/cookies',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  NOT_FOUND: '*',
} as const;

export const getProfileTripHistoryRoute = (tripUniqueId: string): string =>
  `/profile/trips/${encodeURIComponent(tripUniqueId)}/history`;
