<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Google neuron contracts.</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>DigitalBrain.Google</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="IGmail.cs" />
    <Compile Remove="ConnectGmailAccount.cs" />
    <Compile Remove="DisconnectGmail.cs" />
    <Compile Remove="ConfirmGmailDraft.cs" />
    <Compile Remove="RefreshGmailConnection.cs" />
    <Compile Remove="PrepareGmailDraft.cs" />
    <Compile Remove="GmailJson.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../DigitalBrain/Contracts/DigitalBrain.Contracts.csproj" />
  </ItemGroup>
</Project>
