// <auto-generated />
#nullable enable
using DigitalBrain.Core;
using DigitalBrain.Runtime.Runtime;
using DigitalBrain.InoLang;
using DigitalBrain.InoLang.Ast;
using DigitalBrain.InoLang.Linking;
using DigitalBrain.Runtime.Security;
using Microsoft.Extensions.Logging;
using Orleans;
using Orleans.Journaling;
using DigitalBrain.Runtime.Neurons;
using DigitalBrain.Runtime;
using DigitalBrain.SDK.DigitalBrain.Identity;

namespace DigitalBrain.SDK.Identity.Identity;

[global::Orleans.ImplicitStreamSubscription(nameof(GlobalBrainSyncGateNeuron))]
internal sealed class GlobalBrainSyncGateNeuron : Neuron, IHandle<UserBrainSpawned>, INeuronMetadata
{
    public static NeuronId Id => new("identity/global-sync-gate");
    public static string Icon => "sync";
    public static NeuronCapability Capabilities => NeuronCapability.Reasoning;

    private readonly INeuronStateProtector protector;
    private readonly IContractCatalog contractCatalog;
    private readonly IInterpretedNeuronRegistry registry;

    public GlobalBrainSyncGateNeuron(
        [FromKeyedServices("incoming")] IDurableList<Synapse> incoming,
        [FromKeyedServices("outgoing")] IDurableList<Synapse> outgoing,
        IGrainFactory grains,
        ILogger<GlobalBrainSyncGateNeuron> logger,
        IContractCatalog contractCatalog,
        IInterpretedNeuronRegistry registry,
        INeuronStateProtector? protector = null)
        : base(incoming, outgoing, grains, logger)
    {
        this.contractCatalog = contractCatalog;
        this.registry = registry;
        this.protector = protector ?? new PassThroughNeuronStateProtector();
    }

    public async Task HandleAsync(UserBrainSpawned synapse, CancellationToken ct)
    {
        if (synapse.UserId != null)
        {
            Logger.LogInformation("GlobalBrainSyncGateNeuron received UserBrainSpawned for user {UserId}. Triggering sync...", synapse.UserId);
            await SyncUserNeuronsAsync(synapse.UserId);
        }
        else
        {
            Logger.LogWarning("GlobalBrainSyncGateNeuron received UserBrainSpawned without a valid UserId.");
        }
    }

    private async Task SyncUserNeuronsAsync(string userId)
    {
        var privateScope = $"user/{userId}";
        var privateScopeGuid = BrainScopeHelper.ResolveScopeGuid(privateScope);
        var privateRegistry = GrainFactory.GetGrain<INeuronRegistry>(privateScopeGuid);

        try
        {
            var promotedSpecs = await privateRegistry.ListAsync(DynamicNeuronStatus.Promoted);
            if (promotedSpecs == null || promotedSpecs.Count == 0)
            {
                Logger.LogInformation("No promoted dynamic neurons found for user {UserId}.", userId);
                return;
            }

            Logger.LogInformation("Syncing {Count} dynamic neurons from private scope {PrivateScope} to global.", promotedSpecs.Count, privateScope);

            var globalRegistry = GrainFactory.GetGrain<INeuronRegistry>(Guid.Empty);

            foreach (var spec in promotedSpecs)
            {
                try
                {
                    // Save and promote in the global registry
                    await globalRegistry.StageAsync(spec);
                    await globalRegistry.PromoteAsync(spec.Id);

                    // Perform state memory synchronization and boundary merging
                    var privateMemoryKey = $"user/{userId}/{spec.Id.Value}";
                    var globalMemoryKey = spec.Id.Value;

                    var privateMemoryGrain = GrainFactory.GetGrain<INeuronMemoryGrain>(privateMemoryKey);
                    var globalMemoryGrain = GrainFactory.GetGrain<INeuronMemoryGrain>(globalMemoryKey);

                    var privateBytes = await privateMemoryGrain.GetEncryptedMemoryAsync();
                    var globalBytes = await globalMemoryGrain.GetEncryptedMemoryAsync();

                    Dictionary<string, string> privateMemory = [];
                    if (privateBytes is { Length: > 0 })
                    {
                        try
                        {
                            var plaintext = System.Text.Encoding.UTF8.GetString(this.protector.Unprotect(privateBytes));
                            privateMemory = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(plaintext) ?? [];
                        }
                        catch (Exception ex)
                        {
                            Logger.LogWarning(ex, "Failed to decrypt private memory for neuron {NeuronId}.", spec.Id.Value);
                        }
                    }

                    Dictionary<string, string> globalMemory = [];
                    if (globalBytes is { Length: > 0 })
                    {
                        try
                        {
                            var plaintext = System.Text.Encoding.UTF8.GetString(this.protector.Unprotect(globalBytes));
                            globalMemory = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(plaintext) ?? [];
                        }
                        catch (Exception ex)
                        {
                            Logger.LogWarning(ex, "Failed to decrypt global memory for neuron {NeuronId}.", spec.Id.Value);
                        }
                    }

                    // Key-by-key structural merge: private scope overwrites global scope on key collision
                    foreach (var kvp in privateMemory)
                    {
                        globalMemory[kvp.Key] = kvp.Value;
                    }

                    // Encrypt and write the merged memory dictionary back to the global memory grain
                    var mergedJson = System.Text.Json.JsonSerializer.Serialize(globalMemory);
                    var mergedBytes = this.protector.Protect(System.Text.Encoding.UTF8.GetBytes(mergedJson));
                    await globalMemoryGrain.SaveEncryptedMemoryAsync(mergedBytes);

                    // Compile the InoLang source using InoCompiler
                    var compiled = InoCompiler.Compile(spec.FeatureText, contractCatalog);
                    if (!compiled.Success || compiled.Linked == null)
                    {
                        Logger.LogError("Failed to compile dynamic neuron {NeuronId} for sync: {Diagnostics}", spec.Id.Value, string.Join("; ", compiled.Diagnostics.Select(d => d.Message)));
                        continue;
                    }

                    var linked = compiled.Linked;
                    var incoming = linked.Ports.Values
                        .Where(port => port.Decl.Kind == PortKind.Synapse)
                        .Select(port => new IncomingPort(port.Decl.TargetFqn, port.Decl.Name))
                        .ToArray();

                    var outgoing = linked.Ports.Values
                        .Where(port => port.Decl.Kind == PortKind.Synapse)
                        .Select(port => port.Decl.TargetFqn)
                        .ToArray();

                    var descriptor = new NeuronDescriptor(linked.Doc.Fqn, incoming, outgoing, spec.FeatureText);

                    var signalSubscriptions = linked.Doc.Handlers
                        .Select(h => h.Trigger)
                        .OfType<BroadcastTrigger>()
                        .Select(trigger => trigger.Fqn)
                        .Distinct(StringComparer.Ordinal)
                        .OrderBy(fqn => fqn, StringComparer.Ordinal)
                        .ToArray();

                    var registration = new InterpretedNeuronRegistration(descriptor, signalSubscriptions);

                    // Temporarily override RequestContext active scope to "global" when registering
                    var originalScope = RequestContext.Get(BrainScopeHelper.ActiveScopeKey);
                    RequestContext.Set(BrainScopeHelper.ActiveScopeKey, BrainScopeHelper.GlobalScope);
                    try
                    {
                        await registry.RegisterDynamicAsync(registration);
                    }
                    finally
                    {
                        if (originalScope == null)
                            RequestContext.Remove(BrainScopeHelper.ActiveScopeKey);
                        else
                            RequestContext.Set(BrainScopeHelper.ActiveScopeKey, originalScope);
                    }

                    Logger.LogInformation("Successfully synced dynamic neuron {NeuronId} to global.", spec.Id.Value);
                }
                catch (Exception ex)
                {
                    Logger.LogError(ex, "Error syncing dynamic neuron {NeuronId} for user {UserId}.", spec.Id.Value, userId);
                }
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to read private registry for user {UserId}.", userId);
        }
    }
}
