<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IntoChat.Tests.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Testing/DigitalBrain.Testing.Module/DigitalBrain.Testing.Module.csproj" />
    <ProjectReference Include="../../IntoChat/IntoChat.csproj" />
    <ProjectReference Include="../../IntoChat.AppHost/IntoChat.AppHost.csproj" IsAspireProjectResource="false" Aliases="AppHost" />
    <ProjectReference Include="../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
  </ItemGroup>
</Project>
