// <auto-generated />
#nullable enable
using DigitalBrain.Core.Neurons;

namespace DigitalBrain.Navigator
{
    [global::Orleans.ImplicitStreamSubscription(nameof(NavigatorNeuron))]
    public partial class NavigatorNeuron : global::DigitalBrain.Runtime.Neurons.Neuron {}
}

namespace DigitalBrain.Kernel.Settings
{
    [global::Orleans.ImplicitStreamSubscription(nameof(SettingsNeuron))]
    public partial class SettingsNeuron : global::DigitalBrain.Runtime.Neurons.Neuron {}
}
