using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;

namespace DigitalBrain.V2.Ino;

public sealed class InoTranspiler
{
    private static readonly Regex ScenarioEmit = new(
        @"^emit\s+(?<alias>[A-Za-z_][A-Za-z0-9_]*)\((?<args>.*)\)$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private static readonly Regex ScenarioBroadcastObserved = new(
        @"^broadcast\s+(?<alias>[A-Za-z_][A-Za-z0-9_]*)\s+observed(?:\s+with\s+(?<field>[A-Za-z_][A-Za-z0-9_]*)\s*==\s*(?<value>.+))?$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    public GeneratedInoCapsule Transpile(InoProgram program)
    {
        var names = GeneratedNames.From(program.NeuronFqn);
        var code = new CodeBuilder();

        code.Line("// <auto-generated />");
        code.Line("#nullable enable");
        code.Line("#pragma warning disable ORLEANSEXP005");
        code.Line($"namespace {names.Namespace};");
        code.Line("");
        WriteInterface(code, program, names);
        code.Line("");
        WriteNeuron(code, program, names);
        code.Line("");
        WriteSimulation(code, program, names);

        return new GeneratedInoCapsule(
            names.AssemblyName,
            names.InterfaceFullName,
            names.NeuronFullName,
            names.SimulationFullName,
            code.ToString());
    }

    private static void WriteInterface(CodeBuilder code, InoProgram program, GeneratedNames names)
    {
        var edges = new List<string> { "global::DigitalBrain.V2.Core.Runtime.INeuron" };
        edges.AddRange(program.Handles.Select(alias =>
            $"global::DigitalBrain.V2.Core.Runtime.IHandle<{SynapseType(program.Synapse(alias))}>"));
        edges.AddRange(program.Broadcasts.Select(alias =>
            $"global::DigitalBrain.V2.Core.Runtime.IEmit<{SynapseType(program.Synapse(alias))}>"));

        code.Line($"public interface {names.InterfaceName} :");
        code.Indent();
        for (var i = 0; i < edges.Count; i++)
        {
            var suffix = i == edges.Count - 1 ? ";" : ",";
            code.Line(edges[i] + suffix);
        }
        code.Unindent();
    }

    private static void WriteNeuron(CodeBuilder code, InoProgram program, GeneratedNames names)
    {
        code.Line($"public sealed class {names.NeuronName} : global::DigitalBrain.V2.Core.Runtime.Neuron, {names.InterfaceName}");
        code.Line("{");
        code.Indent();

        foreach (var handler in program.Handlers)
        {
            var input = program.Synapse(handler.SynapseAlias);
            code.Line($"public async global::System.Threading.Tasks.Task HandleAsync({SynapseType(input)} synapse, global::System.Threading.CancellationToken ct)");
            code.Line("{");
            code.Indent();
            code.Line($"var {handler.SynapseAlias} = synapse;");

            foreach (var statement in handler.Body)
            {
                WriteStatement(code, program, statement);
            }

            code.Unindent();
            code.Line("}");
            code.Line("");
        }

        code.Unindent();
        code.Line("}");
    }

    private static void WriteStatement(CodeBuilder code, InoProgram program, InoStatement statement)
    {
        switch (statement)
        {
            case SetStateStatement set:
                code.Line($"State[{Literal(set.Name)}] = global::System.Convert.ToString({Expression(program, set.Value)}, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;");
                break;
            case EmitStatement emit:
                code.Line($"await Emit(new {SynapseType(program.Synapse(emit.SynapseAlias))}({Arguments(program, program.Synapse(emit.SynapseAlias), emit.Arguments)}));");
                break;
            case AskStatement ask:
                code.Line($"await Ask<global::{program.Neuron(ask.TargetAlias).Fqn}>(" + Literal("default") + $", new {SynapseType(program.Synapse(ask.SynapseAlias))}({Arguments(program, program.Synapse(ask.SynapseAlias), ask.Arguments)}));");
                break;
            case ReplyStatement reply:
                code.Line($"await Reply(new {SynapseType(program.Synapse(reply.SynapseAlias))}({Arguments(program, program.Synapse(reply.SynapseAlias), reply.Arguments)}));");
                break;
        }
    }

    private static void WriteSimulation(CodeBuilder code, InoProgram program, GeneratedNames names)
    {
        code.Line($"public sealed class {names.SimulationName} : global::DigitalBrain.V2.Testing.Simulation");
        code.Line("{");
        code.Indent();
        code.Line($"protected override global::System.Collections.Generic.IEnumerable<global::System.Reflection.Assembly> ApplicationParts => [typeof({names.NeuronName}).Assembly];");
        code.Line("protected override global::System.Threading.Tasks.Task PrimeAsync() =>");
        code.Indent();
        code.Line("global::Orleans.GrainExtensions.AsReference<global::DigitalBrain.V2.Core.Runtime.INeuron>(");
        code.Indent();
        code.Line($"Grains.GetGrain(global::Orleans.Runtime.GrainId.Create({Literal(names.GrainType)}, {Literal("default")})))");
        code.Unindent();
        code.Line(".EnsureActiveAsync();");
        code.Unindent();
        code.Line("");

        foreach (var scenario in program.Scenarios)
        {
            code.Line("[global::Xunit.Fact]");
            code.Line($"public async global::System.Threading.Tasks.Task {MethodName(scenario.Description)}()");
            code.Line("{");
            code.Indent();

            foreach (var step in scenario.Steps)
            {
                WriteScenarioStep(code, program, step);
            }

            code.Unindent();
            code.Line("}");
            code.Line("");
        }

        code.Unindent();
        code.Line("}");
    }

    private static void WriteScenarioStep(CodeBuilder code, InoProgram program, InoScenarioStep step)
    {
        if (step.Keyword == "when")
        {
            var emit = ScenarioEmit.Match(step.Text);
            if (!emit.Success)
            {
                throw new InoException($"Unsupported scenario stimulus: {step.Text}");
            }

            var synapse = program.Synapse(emit.Groups["alias"].Value);
            code.Line($"await Fire(new {SynapseType(synapse)}({Arguments(program, synapse, ParseScenarioArguments(emit.Groups["args"].Value))}) {{ Routing = global::DigitalBrain.V2.Core.Synapses.RoutingMode.Broadcast }});");
            return;
        }

        if (step.Keyword is "then" or "and")
        {
            var observed = ScenarioBroadcastObserved.Match(step.Text);
            if (!observed.Success)
            {
                throw new InoException($"Unsupported scenario assertion: {step.Text}");
            }

            var synapse = program.Synapse(observed.Groups["alias"].Value);
            var variable = "observed" + Pascal(synapse.Alias);
            if (observed.Groups["field"].Success)
            {
                var field = MemberName(synapse.Fqn, observed.Groups["field"].Value);
                var expected = InoParser.ParseExpression(observed.Groups["value"].Value);
                code.Line($"var {variable} = await Expect<{SynapseType(synapse)}>(s => s.{field} == {Expression(program, expected)});");
                code.Line($"global::Xunit.Assert.Equal({Expression(program, expected)}, {variable}.{field});");
            }
            else
            {
                code.Line($"var {variable} = await Expect<{SynapseType(synapse)}>();");
            }

            code.Line($"global::Xunit.Assert.Equal(global::DigitalBrain.V2.Core.Synapses.RoutingMode.Broadcast, {variable}.Routing);");
        }
    }

    private static InoArgument[] ParseScenarioArguments(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return [];
        }

        var parser = new ScenarioArgumentParser(text);
        return parser.Parse();
    }

    private static string Arguments(InoProgram program, InoSynapsePort synapse, IReadOnlyList<InoArgument> arguments) =>
        string.Join(", ", arguments.Select(arg => $"{MemberName(synapse.Fqn, arg.Name)}: {Expression(program, arg.Value)}"));

    private static string Expression(InoProgram program, InoExpression expression) =>
        expression switch
        {
            StringLiteralExpression literal => Literal(literal.Value),
            RawLiteralExpression raw => raw.Value,
            FieldExpression field => $"{field.Alias}.{MemberName(program.Synapse(field.Alias).Fqn, field.Field)}",
            _ => throw new InoException($"Unsupported expression '{expression.GetType().Name}'.")
        };

    private static string SynapseType(InoSynapsePort port) => "global::" + port.Fqn;

    private static string MemberName(string typeName, string requested)
    {
        var type = FindType(typeName);
        var constructorParameter = type?
            .GetConstructors()
            .SelectMany(ctor => ctor.GetParameters())
            .FirstOrDefault(parameter => string.Equals(parameter.Name, requested, StringComparison.OrdinalIgnoreCase));

        if (constructorParameter?.Name is { } parameterName)
        {
            return Pascal(parameterName);
        }

        var property = type?
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .FirstOrDefault(prop => string.Equals(prop.Name, requested, StringComparison.OrdinalIgnoreCase));

        return property?.Name ?? Pascal(requested);
    }

    private static Type? FindType(string fqn)
    {
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies().Where(assembly => !assembly.IsDynamic))
        {
            try
            {
                var type = assembly.GetType(fqn, throwOnError: false);
                if (type is not null)
                {
                    return type;
                }
            }
            catch
            {
            }
        }

        return null;
    }

    private static string MethodName(string description)
    {
        var builder = new StringBuilder();
        foreach (var c in description)
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        var name = builder.ToString().Trim('_');
        while (name.Contains("__", StringComparison.Ordinal))
        {
            name = name.Replace("__", "_", StringComparison.Ordinal);
        }

        return string.IsNullOrWhiteSpace(name) || !char.IsLetter(name[0])
            ? "Scenario"
            : name;
    }

    private static string Pascal(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        return char.ToUpperInvariant(value[0]) + value[1..];
    }

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal) + "\"";

    private sealed record GeneratedNames(
        string Namespace,
        string InterfaceName,
        string NeuronName,
        string SimulationName,
        string AssemblyName)
    {
        public string GrainType => NeuronName.ToLowerInvariant();
        public string InterfaceFullName => Namespace + "." + InterfaceName;
        public string NeuronFullName => Namespace + "." + NeuronName;
        public string SimulationFullName => Namespace + "." + SimulationName;

        public static GeneratedNames From(string neuronFqn)
        {
            var parts = neuronFqn.Split('.', StringSplitOptions.RemoveEmptyEntries);
            var prefix = string.Concat(parts.Select(Pascal));
            var ns = parts.Length > 1
                ? "DigitalBrain.V2.Generated." + string.Join(".", parts[..^1].Select(Pascal))
                : "DigitalBrain.V2.Generated";

            return new GeneratedNames(
                ns,
                "I" + prefix + "Neuron",
                prefix + "Neuron",
                prefix + "Simulation",
                prefix + ".Ino.Generated");
        }
    }

    private sealed class ScenarioArgumentParser(string text)
    {
        public InoArgument[] Parse()
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return [];
            }

            return Split(text)
                .Select(segment =>
                {
                    var colon = segment.IndexOf(':');
                    if (colon <= 0)
                    {
                        throw new InoException($"Invalid scenario argument: {segment}");
                    }

                    return new InoArgument(
                        segment[..colon].Trim(),
                        InoParser.ParseExpression(segment[(colon + 1)..].Trim()));
                })
                .ToArray();
        }

        private static IReadOnlyList<string> Split(string value)
        {
            var result = new List<string>();
            var builder = new StringBuilder();
            var inString = false;
            var escaped = false;

            foreach (var c in value)
            {
                if (escaped)
                {
                    builder.Append(c);
                    escaped = false;
                    continue;
                }

                if (c == '\\' && inString)
                {
                    builder.Append(c);
                    escaped = true;
                    continue;
                }

                if (c == '"')
                {
                    inString = !inString;
                    builder.Append(c);
                    continue;
                }

                if (c == ',' && !inString)
                {
                    result.Add(builder.ToString().Trim());
                    builder.Clear();
                    continue;
                }

                builder.Append(c);
            }

            if (builder.Length > 0)
            {
                result.Add(builder.ToString().Trim());
            }

            return result;
        }
    }

    private sealed class CodeBuilder
    {
        private readonly StringBuilder _builder = new();
        private int _indent;

        public void Indent() => _indent++;

        public void Unindent() => _indent--;

        public void Line(string text)
        {
            _builder.Append(' ', _indent * 4);
            _builder.AppendLine(text);
        }

        public override string ToString() => _builder.ToString();
    }
}

public sealed record GeneratedInoCapsule(
    string AssemblyName,
    string InterfaceFullName,
    string NeuronFullName,
    string SimulationFullName,
    string Source);
