<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e9789e79-129d-4802-82cf-71931d9466fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ngrok" />
    <PackageReference Include="Aspire.Hosting.Azure.AIFoundry" />
    <PackageReference Include="Aspire.Hosting.Azure.CosmosDB" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.Hosting\Aspire.Hosting.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\DevUI\DevUI.csproj" />
    <ProjectReference Include="..\MCP\MCP.csproj" />
    <ProjectReference Include="..\Agents.Host\Agents.Host.csproj" />
    <ProjectReference Include="..\Telegram\Telegram.csproj" />
  </ItemGroup>

</Project>
