using System.Text.Json.Serialization;
using DigitalBrain.Abstractions.Commands;
using DigitalBrain.Abstractions.Descriptors;
using DigitalBrain.Abstractions.Identity;
using DigitalBrain.Chat;
using DigitalBrain.UI;

[assembly: NeuronJsonContext(typeof(UIJson))]

namespace DigitalBrain.UI;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
[JsonSerializable(typeof(SendMessage))]
[JsonSerializable(typeof(CancelTurn))]
[JsonSerializable(typeof(TurnAccepted))]
[JsonSerializable(typeof(ReadTranscript))]
[JsonSerializable(typeof(ReadTurns))]
[JsonSerializable(typeof(ReadTurn))]
[JsonSerializable(typeof(ContextRef))]
[JsonSerializable(typeof(ContextDigest))]
[JsonSerializable(typeof(ChatTurn))]
[JsonSerializable(typeof(ChatTranscript))]
[JsonSerializable(typeof(ChatTurns))]
[JsonSerializable(typeof(ChatTurnSnapshot))]
[JsonSerializable(typeof(ChatTurnStatus))]
[JsonSerializable(typeof(KitCardOffer))]
[JsonSerializable(typeof(KitCard))]
[JsonSerializable(typeof(Responded))]
[JsonSerializable(typeof(Accepted<SignalId>))]
[JsonSerializable(typeof(SignalId))]
[JsonSerializable(typeof(SurfaceState))]
[JsonSerializable(typeof(SurfaceScene))]
[JsonSerializable(typeof(SurfaceComponent))]
[JsonSerializable(typeof(SurfaceOpenReceipt))]
[JsonSerializable(typeof(ControlActivation))]
[JsonSerializable(typeof(ControlRefused))]
[JsonSerializable(typeof(SurfaceOpened))]
[JsonSerializable(typeof(ComponentAdded))]
[JsonSerializable(typeof(ChartState))]
[JsonSerializable(typeof(ChartPoint))]
[JsonSerializable(typeof(GraphState))]
[JsonSerializable(typeof(GraphNodeState))]
[JsonSerializable(typeof(GraphEdgeState))]
[JsonSerializable(typeof(ImageState))]
[JsonSerializable(typeof(TranscriptState))]
[JsonSerializable(typeof(TranscriptEntry))]
[JsonSerializable(typeof(WorkspaceIndexState))]
[JsonSerializable(typeof(WorkspaceRecord))]
[JsonSerializable(typeof(ActivityExecutionChanged))]
[JsonSerializable(typeof(ActivitiesSnapshot))]
[JsonSerializable(typeof(ActivityChanged))]
[JsonSerializable(typeof(ActivityView))]
[JsonSerializable(typeof(ActivityEventView))]
[JsonSerializable(typeof(OpenSurface))]
[JsonSerializable(typeof(ActivateControl))]
[JsonSerializable(typeof(RenderChart))]
[JsonSerializable(typeof(AppendChartPoint))]
[JsonSerializable(typeof(RenderGraph))]
[JsonSerializable(typeof(DescribeImage))]
[JsonSerializable(typeof(AppendTranscript))]
[JsonSerializable(typeof(EnsureWorkspace))]
[JsonSerializable(typeof(FindWorkspace))]
[JsonSerializable(typeof(ReadActivities))]
[JsonSerializable(typeof(Accepted<SurfaceOpenReceipt>))]
[JsonSerializable(typeof(Accepted<ControlActivation>))]
[JsonSerializable(typeof(Accepted<string>))]
[JsonSerializable(typeof(Accepted<WorkspaceRecord>))]
public sealed partial class UIJson : JsonSerializerContext;
