<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ino.Core\Ino.Core.csproj" />
    <ProjectReference Include="..\..\src\Ino.Core.Hosting\Ino.Core.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Ino.Kernel\Ino.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Ino.Testing\Ino.Testing.csproj" />
    <ProjectReference Include="..\..\domains\travel\Ino.Domains.Travel\Ino.Domains.Travel.csproj" />
  </ItemGroup>

</Project>
