<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ping</RootNamespace>
    <AssemblyName>Ping</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ping.Contracts\Ping.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Ping.ino" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
