const Map<String, String> roleByNodeId = {
  'kernel.cortex': 'Routes user prompts to the matching capability.',
  'kernel.discovery': 'Tracks every neuron registered in the cluster.',
  'kernel.gateway': 'Bridges the Flutter client to the silo over gRPC.',
  'identity.neuron': 'Owns who the user is and which session they are in.',
  'identity.auth': 'Validates the session token on each request.',
  'travel.plan': 'Plans a complete trip end-to-end.',
  'travel.find_flights': 'Picks flights matching the trip brief.',
  'travel.find_hotels': 'Picks hotels matching the trip brief.',
  'travel.find_places': 'Picks places of interest at the destination.',
  'travel.flight_search': 'Calls TripRadar for live flight search.',
  'travel.hotel_search': 'Calls TripRadar for live hotel search.',
  'travel.place_search': 'Calls TripRadar for live place search.',
  'travel.flight_monitor': 'Watches booked flights for delays and changes.',
  'taxi.order_ride': 'Plans an end-to-end ride request.',
  'taxi.ride_request': 'Calls Uber for a live ride.',
  'recall': 'Answers questions about prior synapses.',
  'reminders.neuron': 'Owns the per-user reminder catalogue.',
  'reminders.plan': 'Schedules a reminder from a user prompt.',
  'location.neuron': 'Tracks the current location and known places.',
  'genesis.creator': 'Drafts new neurons proposed by the L1 loop.',
  'genesis.missed': 'Records prompts the cluster could not route.',
  'genesis.optimizer': 'Tunes routing and decay heuristics.',
  'genesis.proposal_log': 'Audit trail of every L1 proposal.',
};
