using System.Text.Json.Serialization;
using Brain.Contracts;

namespace Brain.Kernel;

[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(byte))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(uint))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(ulong))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DateTimeOffset))]
[JsonSerializable(typeof(CommandReceipt))]
[JsonSerializable(typeof(CommandReceiptStatus))]
[JsonSerializable(typeof(SanitizedFailure))]
[JsonSerializable(typeof(OrganizationId))]
[JsonSerializable(typeof(PrincipalId))]
[JsonSerializable(typeof(SpaceId))]
[JsonSerializable(typeof(NeuronAddress))]
[JsonSerializable(typeof(SynapseMetadata))]
[JsonSerializable(typeof(EventSynapse<string>))]
[JsonSerializable(typeof(OutboxIntent<string>))]
[JsonSerializable(typeof(UiAction))]
[JsonSerializable(typeof(UiBlock))]
[JsonSerializable(typeof(UiSurface))]
[JsonSerializable(typeof(UiSurfaceSnapshot))]
[JsonSerializable(typeof(UiPatchOperation))]
[JsonSerializable(typeof(UiSurfacePatch))]
[JsonSerializable(typeof(UiFeedCandidate))]
[JsonSerializable(typeof(EventSynapse<UiFeedCandidate>))]
[JsonSerializable(typeof(UiFeedFrame))]
[JsonSerializable(typeof(UiFeedPage))]
public sealed partial class ReactiveJournalJsonContext : JsonSerializerContext;
