<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Ino.NeuronTesting\Ino.NeuronTesting.csproj" />
    <ProjectReference Include="..\..\..\src\Ino.NeuronTesting.Bdd\Ino.NeuronTesting.Bdd.csproj" />
    <ProjectReference Include="..\..\..\src\Ino.AppHost.Testing\Ino.AppHost.Testing.csproj" />
    <ProjectReference Include="..\Ino.Domains.Travel\Ino.Domains.Travel.csproj" />
  </ItemGroup>
</Project>
