<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

interface DiagramNode {
  label: string
  description: string
  link?: string
}

interface ArrowDef {
  x1: number; y1: number; x2: number; y2: number
  from: string; to: string
}

const clusterIds = new Set(['orchestration', 'infrastructure', 'csharp', 'memory', 'llm'])

const nodes: Record<string, DiagramNode> = {
  telegram: {
    label: 'Telegram',
    description: 'Telegram bot client handling text messages, voice transcription (OGG\u2192WAV\u2192Whisper), callback queries, and forum topics. Coordinates with ThreadAgent for LLM responses and uses TelegramUIAgent for rich formatting.',
    link: '/IAW/guide/telegram-bot',
  },
  mcp: {
    label: 'MCP',
    description: 'ModelContextProtocol server on port 5300 exposing seven agent tools: agent_list_all, assistant_chat, agent_send_message, agent_get_status, agent_assign_task, agent_get_events, and agent_get_metrics.',
    link: '/IAW/guide/mcp-server',
  },
  devui: {
    label: 'DevUI',
    description: 'Blazor web UI connecting to the Orleans cluster as an IAW client via AddIAWClient(). Provides a development-focused interface for agent interaction and debugging.',
  },
  orchestration: {
    label: 'Orchestration',
    description: 'Three agents manage request routing: ThreadAgent receives all messages and picks the path, AgentSelectorAgent uses LLM to find the best agent team, and CodeOrchestratorAgent generates C# scripts for complex multi-agent workflows.',
    link: '/IAW/guide/orchestration',
  },
  infrastructure: {
    label: 'Infrastructure',
    description: 'Shell (command execution), FileSystem (workspace I/O), Git (version control), Aspire (deployment via MCP), and IAWSystem (coordinator). Most use [Llm<Fast>] for lightweight reasoning.',
    link: '/IAW/guide/tools',
  },
  csharp: {
    label: 'C#',
    description: 'Roslyn (AST analysis via Microsoft.CodeAnalysis), DotNet (build/test/format), GitHub (release watching, issues), and NuGet (package update monitoring via nuget.org API).',
    link: '/IAW/guide/building-agents',
  },
  memory: {
    label: 'Memory',
    description: 'Five grains \u2014 UserMemory, ProjectMemory, PatternMemory, EpisodeMemory, CodeMemory \u2014 each with Qdrant vector embeddings for semantic search and daily decay/consolidation maintenance.',
    link: '/IAW/guide/memory',
  },
  llm: {
    label: 'LLM',
    description: '14 agents wrapping specific models via [Llm<T>]: Claude (Haiku/Sonnet/Opus), GPT (4o/Mini/5.2/5.3/5.4), Gemini, Grok, Llama, Qwen. Used for model fan-out and comparison.',
    link: '/IAW/guide/llm-agents',
  },
  azurite: {
    label: 'Azurite',
    description: 'Azure Blob Storage emulator managed by Aspire. Stores documents, uploaded files, and conversation attachments. Configured via AddIAW() in the AppHost.',
  },
  qdrant: {
    label: 'Qdrant',
    description: 'Vector database for semantic search across five memory collections and RAG document retrieval. Embeddings generated by the configured IEmbeddingGenerator.',
    link: '/IAW/guide/persistence',
  },
  llmapis: {
    label: 'LLM APIs',
    description: 'External model providers wired via WithLLM<T>().AsFast/AsBalanced/AsReasoning(). Supports OpenAI, Anthropic, Ollama (local), and GitHub Models.',
    link: '/IAW/guide/llm-agents',
  },
}

const arrows: ArrowDef[] = [
  { x1: 118, y1: 78, x2: 165, y2: 78, from: 'telegram', to: '_cluster' },
  { x1: 118, y1: 128, x2: 165, y2: 128, from: 'mcp', to: '_cluster' },
  { x1: 118, y1: 178, x2: 165, y2: 178, from: 'devui', to: '_cluster' },
  { x1: 715, y1: 78, x2: 762, y2: 78, from: '_cluster', to: 'azurite' },
  { x1: 715, y1: 128, x2: 762, y2: 128, from: '_cluster', to: 'qdrant' },
  { x1: 715, y1: 178, x2: 762, y2: 178, from: '_cluster', to: 'llmapis' },
]

const particles = computed(() =>
  arrows.map((a, i) => ({
    path: `M${a.x1},${a.y1} L${a.x2},${a.y2}`,
    dur: '1.8s',
    delay: `${(i * 0.6).toFixed(1)}s`,
  })),
)

const wrapperRef = ref<HTMLElement | null>(null)
const visible = ref(false)
const hoveredNode = ref<string | null>(null)
const lockedNode = ref<string | null>(null)
const activeNode = computed(() => lockedNode.value ?? hoveredNode.value)

onMounted(() => {
  const obs = new IntersectionObserver(
    ([e]) => { if (e.isIntersecting) { visible.value = true; obs.disconnect() } },
    { threshold: 0.1 },
  )
  if (wrapperRef.value) obs.observe(wrapperRef.value)
})

function onEnter(id: string) { if (!lockedNode.value) hoveredNode.value = id }
function onLeave() { if (!lockedNode.value) hoveredNode.value = null }
function onClick(id: string) {
  if (lockedNode.value === id) { lockedNode.value = null; hoveredNode.value = null }
  else { lockedNode.value = id; hoveredNode.value = id }
}

function nc(id: string): string {
  const a = activeNode.value
  if (!a) return 'node'
  return a === id ? 'node node-active' : 'node node-dimmed'
}

function ac(from: string, to: string): string {
  const a = activeNode.value
  if (!a) return ''
  const fromHit = a === from || (from === '_cluster' && clusterIds.has(a))
  const toHit = a === to || (to === '_cluster' && clusterIds.has(a))
  if (fromHit) return 'arrow-active'
  if (toHit) return 'arrow-incoming'
  return 'arrow-dimmed'
}

function am(from: string): string {
  const a = activeNode.value
  const hit = a === from || (from === '_cluster' && clusterIds.has(a!))
  return hit ? 'url(#ah-brand)' : 'url(#ah)'
}
</script>

<template>
  <div ref="wrapperRef" class="arch-wrapper" :class="{ visible }">
    <div class="arch-canvas">
      <svg class="arch-svg" viewBox="0 0 880 330" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <marker id="ah" viewBox="0 0 10 7" refX="10" refY="3.5" markerWidth="7" markerHeight="5" orient="auto">
            <path d="M0,0 L10,3.5 L0,7Z" class="mk" />
          </marker>
          <marker id="ah-brand" viewBox="0 0 10 7" refX="10" refY="3.5" markerWidth="7" markerHeight="5" orient="auto">
            <path d="M0,0 L10,3.5 L0,7Z" class="mk-b" />
          </marker>
        </defs>

        <!-- Particles -->
        <g class="row row-particles">
          <circle v-for="(p, i) in particles" :key="i" r="2.5" class="particle">
            <animateMotion :dur="p.dur" :begin="p.delay" repeatCount="indefinite" :path="p.path" />
          </circle>
        </g>

        <!-- Arrows -->
        <g class="row row-arrows">
          <g v-for="(a, i) in arrows" :key="i" :class="['ag', ac(a.from, a.to)]">
            <line :x1="a.x1" :y1="a.y1" :x2="a.x2" :y2="a.y2" class="al" :marker-end="am(a.from)" />
          </g>
        </g>

        <!-- ===== Aspire AppHost border ===== -->
        <g class="row row-frame">
          <rect class="aspire-border" x="12" y="12" width="856" height="306" rx="14" />
          <rect class="label-bg" x="25" y="3" width="132" height="18" rx="4" />
          <text x="91" y="16" class="frame-label">ASPIRE APPHOST</text>
        </g>

        <!-- ===== Orleans Cluster ===== -->
        <g class="row row-cluster">
          <rect class="cluster-bg" x="165" y="28" width="550" height="275" rx="12" />
          <rect class="cluster-border" x="165" y="28" width="550" height="275" rx="12" />
          <rect class="label-bg" x="178" y="19" width="130" height="18" rx="4" />
          <text x="243" y="32" class="frame-label">ORLEANS CLUSTER</text>

          <!-- Agent group blocks -->
          <g :class="nc('orchestration')" @mouseenter="onEnter('orchestration')" @mouseleave="onLeave" @click="onClick('orchestration')">
            <rect x="178" y="52" width="165" height="85" rx="8" />
            <text x="260" y="80" class="bl">Orchestration</text>
            <text x="260" y="98" class="bs">Thread &#xb7; Selector</text>
            <text x="260" y="112" class="bs">CodeOrchestrator</text>
          </g>
          <g :class="nc('infrastructure')" @mouseenter="onEnter('infrastructure')" @mouseleave="onLeave" @click="onClick('infrastructure')">
            <rect x="353" y="52" width="165" height="85" rx="8" />
            <text x="435" y="80" class="bl">Infrastructure</text>
            <text x="435" y="98" class="bs">Shell &#xb7; FS &#xb7; Git</text>
            <text x="435" y="112" class="bs">Aspire &#xb7; System</text>
          </g>
          <g :class="nc('csharp')" @mouseenter="onEnter('csharp')" @mouseleave="onLeave" @click="onClick('csharp')">
            <rect x="538" y="52" width="165" height="85" rx="8" />
            <text x="620" y="80" class="bl">C#</text>
            <text x="620" y="98" class="bs">Roslyn &#xb7; DotNet</text>
            <text x="620" y="112" class="bs">GitHub &#xb7; NuGet</text>
          </g>
          <g :class="nc('memory')" @mouseenter="onEnter('memory')" @mouseleave="onLeave" @click="onClick('memory')">
            <rect x="230" y="152" width="165" height="85" rx="8" />
            <text x="312" y="180" class="bl">Memory</text>
            <text x="312" y="198" class="bs">5 agents</text>
            <text x="312" y="212" class="bs">Qdrant search</text>
          </g>
          <g :class="nc('llm')" @mouseenter="onEnter('llm')" @mouseleave="onLeave" @click="onClick('llm')">
            <rect x="455" y="152" width="165" height="85" rx="8" />
            <text x="537" y="180" class="bl">LLM</text>
            <text x="537" y="198" class="bs">14 models</text>
            <text x="537" y="212" class="bs">multi-provider</text>
          </g>
        </g>

        <!-- ===== Clients column ===== -->
        <g class="row row-clients">
          <text x="73" y="50" class="col-header">CLIENTS</text>
          <g :class="nc('telegram')" @mouseenter="onEnter('telegram')" @mouseleave="onLeave" @click="onClick('telegram')">
            <rect x="28" y="58" width="90" height="40" rx="10" />
            <text x="73" y="83" class="nl">Telegram</text>
          </g>
          <g :class="nc('mcp')" @mouseenter="onEnter('mcp')" @mouseleave="onLeave" @click="onClick('mcp')">
            <rect x="28" y="108" width="90" height="40" rx="10" />
            <text x="73" y="133" class="nl">MCP</text>
          </g>
          <g :class="nc('devui')" @mouseenter="onEnter('devui')" @mouseleave="onLeave" @click="onClick('devui')">
            <rect x="28" y="158" width="90" height="40" rx="10" />
            <text x="73" y="183" class="nl">DevUI</text>
          </g>
        </g>

        <!-- ===== Resources column ===== -->
        <g class="row row-resources">
          <text x="807" y="50" class="col-header">RESOURCES</text>
          <g :class="nc('azurite')" @mouseenter="onEnter('azurite')" @mouseleave="onLeave" @click="onClick('azurite')">
            <rect x="762" y="58" width="90" height="40" rx="10" />
            <text x="807" y="83" class="nl">Azurite</text>
          </g>
          <g :class="nc('qdrant')" @mouseenter="onEnter('qdrant')" @mouseleave="onLeave" @click="onClick('qdrant')">
            <rect x="762" y="108" width="90" height="40" rx="10" />
            <text x="807" y="133" class="nl">Qdrant</text>
          </g>
          <g :class="nc('llmapis')" @mouseenter="onEnter('llmapis')" @mouseleave="onLeave" @click="onClick('llmapis')">
            <rect x="762" y="158" width="90" height="40" rx="10" />
            <text x="807" y="183" class="nl">LLM APIs</text>
          </g>
        </g>
      </svg>
    </div>

    <!-- Description Panel -->
    <div class="dp" :class="{ 'dp-active': activeNode }">
      <Transition name="fade" mode="out-in">
        <div v-if="activeNode" :key="activeNode" class="dp-body">
          <div class="dp-head">
            <h3>{{ nodes[activeNode].label }}</h3>
            <span v-if="lockedNode" class="dp-hint">click to unlock</span>
          </div>
          <p>{{ nodes[activeNode].description }}</p>
          <a v-if="nodes[activeNode].link" :href="nodes[activeNode].link" class="dp-link">Learn more &rarr;</a>
        </div>
        <p v-else key="default" class="dp-empty">&#x1F446; Hover any component to explore &#xb7; click to lock</p>
      </Transition>
    </div>
  </div>
</template>

<style scoped>
/* ── Layout ── */
.arch-wrapper { max-width: 920px; margin: 32px auto; overflow-x: auto; }
.arch-canvas {
  background: var(--vp-c-bg-alt);
  border: 1px solid var(--vp-c-divider);
  border-radius: 14px;
  padding: 8px 4px;
}
.arch-svg { width: 100%; min-width: 600px; height: auto; display: block; }

/* ── Entrance ── */
.row { opacity: 0; transform: translateY(14px); }
.visible .row { animation: enter 0.5s ease-out forwards; }
.visible .row-frame     { animation-delay: 0.05s; }
.visible .row-clients   { animation-delay: 0.12s; }
.visible .row-cluster   { animation-delay: 0.22s; }
.visible .row-resources { animation-delay: 0.32s; }
.visible .row-arrows    { animation-delay: 0.42s; }
.visible .row-particles { animation-delay: 0.55s; }
@keyframes enter {
  from { opacity: 0; transform: translateY(14px); }
  to   { opacity: 1; transform: translateY(0); }
}

/* ── Particles ── */
.particle { fill: var(--vp-c-brand-1); opacity: 0.35; }

/* ── Aspire border ── */
.aspire-border {
  fill: none;
  stroke: var(--vp-c-brand-1);
  stroke-width: 1.2;
  opacity: 0.5;
}

/* ── Cluster ── */
.cluster-bg { fill: var(--vp-c-bg-soft); opacity: 0.4; }
.cluster-border {
  fill: none;
  stroke: var(--vp-c-divider);
  stroke-width: 1;
  stroke-dasharray: 5 4;
  animation: drift 14s linear infinite;
}
@keyframes drift { to { stroke-dashoffset: -36; } }

/* ── Labels ── */
.label-bg { fill: var(--vp-c-bg-alt); stroke: none; }
.frame-label {
  fill: var(--vp-c-brand-1);
  font-family: var(--vp-font-family-base);
  font-size: 10px;
  font-weight: 700;
  text-anchor: middle;
  letter-spacing: 0.8px;
  pointer-events: none;
  opacity: 0.7;
}
.col-header {
  fill: var(--vp-c-text-3);
  font-family: var(--vp-font-family-base);
  font-size: 8.5px;
  font-weight: 600;
  text-anchor: middle;
  letter-spacing: 1.2px;
  pointer-events: none;
}

/* ── Arrows ── */
.al {
  stroke: var(--vp-c-divider);
  stroke-width: 1.2;
  fill: none;
  transition: stroke 0.25s, stroke-width 0.25s;
}
.ag { transition: opacity 0.3s; }
.arrow-active .al {
  stroke: var(--vp-c-brand-1);
  stroke-width: 1.8;
  stroke-dasharray: 6 3;
  animation: flow 0.45s linear infinite;
}
.arrow-incoming { opacity: 0.4; }
.arrow-dimmed   { opacity: 0.15; }
@keyframes flow { to { stroke-dashoffset: -9; } }
.mk   { fill: var(--vp-c-divider); }
.mk-b { fill: var(--vp-c-brand-1); }

/* ── Nodes ── */
.node { cursor: pointer; transition: opacity 0.3s; }
.node rect {
  fill: var(--vp-c-bg-soft);
  stroke: var(--vp-c-divider);
  stroke-width: 1;
  transition: stroke 0.2s, filter 0.3s, stroke-width 0.2s;
}
.node:hover rect { stroke: var(--vp-c-text-3); }
.node-active rect {
  stroke: var(--vp-c-brand-1);
  stroke-width: 1.5;
  animation: glow 2.4s ease-in-out infinite;
}
.node-dimmed { opacity: 0.2; }
@keyframes glow {
  0%, 100% { filter: drop-shadow(0 0 3px var(--vp-c-brand-soft)); }
  50%      { filter: drop-shadow(0 0 9px var(--vp-c-brand-soft)); }
}

/* ── Node text ── */
.nl {
  fill: var(--vp-c-text-1);
  font-family: var(--vp-font-family-base);
  font-size: 12px;
  font-weight: 600;
  text-anchor: middle;
  pointer-events: none;
}
.bl {
  fill: var(--vp-c-brand-1);
  font-family: var(--vp-font-family-base);
  font-size: 11.5px;
  font-weight: 700;
  text-anchor: middle;
  pointer-events: none;
}
.bs {
  fill: var(--vp-c-text-3);
  font-family: var(--vp-font-family-base);
  font-size: 9px;
  text-anchor: middle;
  pointer-events: none;
}

/* ── Description panel ── */
.dp {
  margin-top: 14px;
  padding: 14px 18px;
  border-radius: 10px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg-soft);
  min-height: 56px;
  transition: border-color 0.3s, box-shadow 0.3s;
  opacity: 0; transform: translateY(8px);
}
.visible .dp { animation: enter 0.45s ease-out 0.6s forwards; }
.dp-active {
  border-color: var(--vp-c-brand-1);
  box-shadow: 0 0 20px -6px var(--vp-c-brand-soft);
}
.dp-head { display: flex; justify-content: space-between; align-items: baseline; }
.dp-head h3 { margin: 0 0 4px; font-size: 15px; font-weight: 600; color: var(--vp-c-text-1); }
.dp p { margin: 0; font-size: 14px; line-height: 1.55; color: var(--vp-c-text-2); }
.dp-link {
  display: inline-block; margin-top: 6px; font-size: 13px;
  color: var(--vp-c-brand-1); text-decoration: none; font-weight: 500;
}
.dp-link:hover { text-decoration: underline; }
.dp-hint { font-size: 11px; color: var(--vp-c-text-3); white-space: nowrap; }
.dp-empty { text-align: center; color: var(--vp-c-text-3) !important; padding: 6px 0; }

/* ── Panel transition ── */
.fade-enter-active { transition: opacity 0.18s, transform 0.18s; }
.fade-leave-active { transition: opacity 0.1s; }
.fade-enter-from   { opacity: 0; transform: translateY(4px); }
.fade-leave-to     { opacity: 0; }
</style>
