<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>Ino.Domains.Location</RootNamespace>
    <AssemblyName>Ino.Domains.Location</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Ino.Core\Ino.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Ino.Core.Hosting\Ino.Core.Hosting.csproj" />
    <ProjectReference Include="..\..\..\src\Ino.ServiceDefaults\Ino.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\src\Ino.Llm.Xai\Ino.Llm.Xai.csproj" />
    <ProjectReference Include="..\Ino.Domains.Location.Contracts\Ino.Domains.Location.Contracts.csproj" />
  </ItemGroup>

</Project>
