using System.Text.Json.Serialization;
using DigitalBrain.Core;
using DigitalBrain.Developer;

namespace DigitalBrain.Kernel;

[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(uint))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DateTimeOffset))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(Synapse))]
[JsonSerializable(typeof(NeuronId))]
[JsonSerializable(typeof(Checkpoint))]
[JsonSerializable(typeof(NeuronActivated))]
[JsonSerializable(typeof(DistributedAppStarted))]
[JsonSerializable(typeof(RestartResource))]
[JsonSerializable(typeof(StartDistributedApp))]
[JsonSerializable(typeof(ListPublished))]
[JsonSerializable(typeof(CreateNeuronRequest))]
[JsonSerializable(typeof(NeuronCodeGenerated))]
[JsonSerializable(typeof(NeuronTelemetry))]
[JsonSerializable(typeof(WiringOptimizationProposed))]
[JsonSerializable(typeof(DemoMessageSynapse))]
[JsonSerializable(typeof(ExperienceUsed))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginSucceeded))]
[JsonSerializable(typeof(LoginFailed))]
[JsonSerializable(typeof(LogoutRequest))]
[JsonSerializable(typeof(UserSessionCreated))]
[JsonSerializable(typeof(UserSessionEnded))]
[JsonSerializable(typeof(LocalUserRegistered))]
[JsonSerializable(typeof(UserSessionState))]
[JsonSerializable(typeof(LlmPrompt))]
[JsonSerializable(typeof(LlmResponse))]
[JsonSerializable(typeof(CreateSimpleApp))]
[JsonSerializable(typeof(SimpleAppCreated))]
[JsonSerializable(typeof(SystemLaunched))]
[JsonSerializable(typeof(SystemStatusChanged))]
[JsonSerializable(typeof(FixProposal))]
[JsonSerializable(typeof(SimulationResult))]
[JsonSerializable(typeof(PublishToMarketplace))]
[JsonSerializable(typeof(InstallFromMarketplace))]
[JsonSerializable(typeof(FilterMarketplace))]
[JsonSerializable(typeof(NeuroPackInstalled))]
[JsonSerializable(typeof(PublishedList))]
[JsonSerializable(typeof(CommissionTaken))]
[JsonSerializable(typeof(BranchCreated))]
[JsonSerializable(typeof(InoRequest))]
[JsonSerializable(typeof(InoResponse))]
[JsonSerializable(typeof(MemorySummary))]
[JsonSerializable(typeof(InoCodeEdit))]
[JsonSerializable(typeof(InoCodeRun))]
[JsonSerializable(typeof(NuGetCommand))]
[JsonSerializable(typeof(NuGetResult))]
[JsonSerializable(typeof(ArchitectRequest))]
[JsonSerializable(typeof(ArchitectReport))]
[JsonSerializable(typeof(ArchitectResult))]
[JsonSerializable(typeof(ClosedLoopRequest))]
[JsonSerializable(typeof(InoCodeSave))]
[JsonSerializable(typeof(InoCodeExecute))]
[JsonSerializable(typeof(InoCodeApplySkill))]
[JsonSerializable(typeof(SkillContextInjected))]
[JsonSerializable(typeof(ContextUpdate))]
[JsonSerializable(typeof(DbConnect))]
[JsonSerializable(typeof(DbQuery))]
[JsonSerializable(typeof(FilterChanged))]
[JsonSerializable(typeof(ClusterActivity))]
[JsonSerializable(typeof(ThreeDGraphUpdate))]
[JsonSerializable(typeof(VisualizeDataRequest))]
[JsonSerializable(typeof(DataChartGenerated))]
[JsonSerializable(typeof(DataChartFailed))]
[JsonSerializable(typeof(ChartCommand))]
[JsonSerializable(typeof(ChartInteraction))]
[JsonSerializable(typeof(GraphicSpec))]
[JsonSerializable(typeof(WidgetTreeInspected))]
[JsonSerializable(typeof(UIModificationProposed))]
[JsonSerializable(typeof(SystemModificationProposed))]
[JsonSerializable(typeof(ClosedLoopCompleted))]
// Foundry synapses
[JsonSerializable(typeof(GenerateCode))]
[JsonSerializable(typeof(CodeGenerated))]
[JsonSerializable(typeof(RunGeneratedCode))]
[JsonSerializable(typeof(CodeRunResult))]
[JsonSerializable(typeof(DeployGeneratedCode))]
[JsonSerializable(typeof(CodeBuilt))]
[JsonSerializable(typeof(SiloRestartRequested))]
[JsonSerializable(typeof(FoundryRequest))]
[JsonSerializable(typeof(FoundryCheckpointed))]
[JsonSerializable(typeof(FoundryCompleted))]
[JsonSerializable(typeof(FoundryRolledBack))]
// UI surface synapses
[JsonSerializable(typeof(UiSurface))]
[JsonSerializable(typeof(ChartSpec))]
[JsonSerializable(typeof(AuthButtonSurface))]
[JsonSerializable(typeof(ListSurface))]
[JsonSerializable(typeof(IdeSurface))]
// SDK integration-neuron synapses
[JsonSerializable(typeof(GitCommitted))]
[JsonSerializable(typeof(GitReverted))]
// Distribution / embodiment
[JsonSerializable(typeof(PackEmission))]
[JsonSerializable(typeof(ConfigurationProvided))]
// Company brain knowledge + skills (ingest, crystallize, refund vertical outcomes)
[JsonSerializable(typeof(IngestCompanySource))]
[JsonSerializable(typeof(CompanySourceIngested))]
[JsonSerializable(typeof(CrystallizeProcess))]
[JsonSerializable(typeof(ProcessSpecCrystallized))]
[JsonSerializable(typeof(RefundRequested))]
[JsonSerializable(typeof(RefundApproved))]
[JsonSerializable(typeof(RefundDenied))]
[JsonSerializable(typeof(ProcessSpec))]
[JsonSerializable(typeof(DecisionPoint))]
[JsonSerializable(typeof(CreateCompanySkill))]
[JsonSerializable(typeof(CompanySkillCreationResult))]
// Awesome / software-engineering review
[JsonSerializable(typeof(ReviewRequest))]
[JsonSerializable(typeof(ReviewProjectRequest))]
[JsonSerializable(typeof(ReviewResult))]
// Context / semantic memory
[JsonSerializable(typeof(MemoryStored))]
// Economics / licensing
[JsonSerializable(typeof(LicenseGranted))]
[JsonSerializable(typeof(LicenseKeyPair))]
// Server-driven UI
[JsonSerializable(typeof(RfwCard))]
[JsonSerializable(typeof(PerformKernelSelfUpdate))]
// Experience domain
[JsonSerializable(typeof(ExperienceStep))]
// Generic protocol carriers (pack-defined events and LLM intents)
[JsonSerializable(typeof(DigitalBrain.Core.Signal))]
[JsonSerializable(typeof(DigitalBrain.Core.AskLlm))]
// Task records (universal core protocol, used by kernel grain + INO + MCP)
[JsonSerializable(typeof(DigitalBrain.Core.TaskCreated))]
[JsonSerializable(typeof(DigitalBrain.Core.TaskStarted))]
[JsonSerializable(typeof(DigitalBrain.Core.TaskProgress))]
[JsonSerializable(typeof(DigitalBrain.Core.TaskCompleted))]
[JsonSerializable(typeof(DigitalBrain.Core.TaskCancelled))]
[JsonSerializable(typeof(DigitalBrain.Core.RunTask))]
[JsonSerializable(typeof(DigitalBrain.Core.CancelTask))]
public partial class JournalJsonContext : JsonSerializerContext;
