<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DigitalBrain.Kernel.Contracts\DigitalBrain.Kernel.Contracts.csproj" />
    <ProjectReference Include="..\DigitalBrain.Integrations.Salesforce.Contracts\DigitalBrain.Integrations.Salesforce.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\features\EnrichSalesforce\DigitalBrain.Features.EnrichSalesforce.csproj" LogicalName="DigitalBrain.FeatureTemplates.EnrichSalesforce.DigitalBrain.Features.EnrichSalesforce.csproj" />
    <EmbeddedResource Include="..\..\features\EnrichSalesforce\EnrichSalesforce.cs" LogicalName="DigitalBrain.FeatureTemplates.EnrichSalesforce.EnrichSalesforce.cs" />
    <EmbeddedResource Include="..\..\features\EnrichSalesforce.Tests\DigitalBrain.Features.EnrichSalesforce.Tests.csproj" LogicalName="DigitalBrain.FeatureTemplates.EnrichSalesforce.DigitalBrain.Features.EnrichSalesforce.Tests.csproj" />
    <EmbeddedResource Include="..\..\features\EnrichSalesforce.Tests\EnrichSalesforce.feature" LogicalName="DigitalBrain.FeatureTemplates.EnrichSalesforce.EnrichSalesforce.feature" />
    <EmbeddedResource Include="..\..\features\EnrichSalesforce.Tests\EnrichSalesforceSteps.cs" LogicalName="DigitalBrain.FeatureTemplates.EnrichSalesforce.EnrichSalesforceSteps.cs" />
    <EmbeddedResource Include="..\..\features\EnrichSalesforce.Tests\reqnroll.json" LogicalName="DigitalBrain.FeatureTemplates.EnrichSalesforce.reqnroll.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DeveloperForce.Force" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="DigitalBrain.Integrations.Salesforce.Grains" />
  </ItemGroup>

</Project>
