<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../../Apps/DigitalBrain.Modules.Apps.csproj" />
  </ItemGroup>
</Project>
