<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Brain.Abstractions/Brain.Abstractions.csproj" />
  </ItemGroup>
</Project>
