<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>$(NoWarn);CA2007;CA1515;CA1062</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalBrain.Mocks\DigitalBrain.Mocks.csproj" />
    <ProjectReference Include="..\DigitalBrain.Testing\DigitalBrain.Testing.csproj" />
    <ProjectReference Include="..\DigitalBrain.Testing.Mechanics\DigitalBrain.Testing.Mechanics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
