<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
    <ProjectReference Include="../../../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
    <ProjectReference Include="../../CSharp/DigitalBrain.Modules.Microsoft.CSharp.csproj" />
    <ProjectReference Include="../../../../Time/Time/DigitalBrain.Modules.Time.csproj" />
  </ItemGroup>
</Project>
