<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
    <ProjectReference Include="../../Aspire.Hosting/DigitalBrain.Modules.Microsoft.CSharp.Aspire.Hosting.csproj" />
    <ProjectReference Include="../../../Aspire/Aspire.Hosting/DigitalBrain.Modules.Microsoft.Aspire.Aspire.Hosting.csproj" />
    <ProjectReference Include="../../../../Time/Time/DigitalBrain.Modules.Time.csproj" />
  </ItemGroup>
</Project>
