// <auto-generated />
#nullable enable
using DigitalBrain.Core.Neurons;

namespace DigitalBrain.SDK.Identity
{
    [global::Orleans.ImplicitStreamSubscription(nameof(IdentityNeuron))]
    public partial class IdentityNeuron : global::DigitalBrain.Runtime.Neurons.Neuron {}

    [global::Orleans.ImplicitStreamSubscription(nameof(BootOrchestrator))]
    public partial class BootOrchestrator : global::DigitalBrain.Runtime.Neurons.Neuron {}
}

namespace DigitalBrain.Domains.Onboarding
{
    [global::Orleans.ImplicitStreamSubscription(nameof(OnboardingNeuron))]
    public partial class OnboardingNeuron : global::DigitalBrain.Runtime.Neurons.Neuron {}
}

namespace DigitalBrain.Assistant.Core.Specs
{
    [global::Orleans.ImplicitStreamSubscription(nameof(PersonalAssistant))]
    public partial class PersonalAssistant : global::DigitalBrain.Runtime.Neurons.Neuron {}
}

namespace DigitalBrain.SDK.Windows
{
    [global::Orleans.ImplicitStreamSubscription(nameof(MicrosoftWindows))]
    public partial class MicrosoftWindows : global::DigitalBrain.Runtime.Neurons.Neuron {}
}

namespace DigitalBrain.SDK.Aspire.Runtime.Specs
{
    [global::Orleans.ImplicitStreamSubscription(nameof(SelfHealing))]
    public partial class SelfHealing : global::DigitalBrain.Runtime.Neurons.Neuron {}
}
