<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../../../../Modules/DigitalBrain/Specs/Specs/DigitalBrain.Modules.Specs.csproj" />
    <ProjectReference Include="../../DigitalBrain.Apps.Assistant.csproj" />
    <ProjectReference Include="../../../../Modules/Supabase/Supabase/DigitalBrain.Modules.Supabase.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="assistant.feature" LogicalName="assistant.feature" />
  </ItemGroup>
</Project>
