<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>DigitalBrain.Testing.Unit.Tests.Unit</RootNamespace></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <ProjectReference Include="../DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <None Update="Identity/LegacyState/*.orleans" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
