<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DigitalBrain.Modules.Identity.Tests.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
    <ProjectReference Include="../DigitalBrain.Modules.Identity/DigitalBrain.Modules.Identity.csproj" />
  </ItemGroup>
</Project>
