using DigitalBrain.V2.Core.Runtime;

namespace DigitalBrain.V2.Creator;

public sealed class ImplementerNeuron : Neuron, IImplementerNeuron
{
    public Task HandleAsync(ImplementNeuron synapse, CancellationToken ct) =>
        Reply(new NeuronAuthored(synapse.Capability, PingEchoIno, synapse.Attempt));

    private const string PingEchoIno = """
neuron Generated.PingEcho
  "Generated by the v2 creator loop."

  using ping = synapse(Ping.Contracts.Ping)
  using pong = synapse(Ping.Contracts.Pong)

  broadcasts pong
  handles    ping

  state lastSeen: text

  on ping:
    set lastSeen = ping.from
    emit pong(to: ping.from)

scenario "generated ping is echoed"
  when  emit ping(from: "loop")
  then  broadcast pong observed with to == "loop"
""";
}
