using DigitalBrain.V2.Core.Runtime;
using DigitalBrain.V2.Core.Synapses;
using Microsoft.Extensions.AI;

namespace DigitalBrain.V2.Creator;

public interface ILlmNeuron :
    INeuron,
    IHandle<LlmPrompt>,
    IHandle<NeuronAuthored>,
    IEmit<LlmCompletion>;

[GenerateSerializer]
public sealed record LlmPrompt(
    [property: Id(0)] string Capability,
    [property: Id(1)] string SystemPrompt,
    [property: Id(2)] string UserPrompt,
    [property: Id(3)] int Attempt) : Synapse;

[GenerateSerializer]
public sealed record LlmCompletion(
    [property: Id(0)] string Capability,
    [property: Id(1)] string InoSource,
    [property: Id(2)] string[] Diagnostics) : Synapse;

// Structured draft for reliable LLM output via GetResponseAsync<InoDraft>
public sealed record InoDraft(string InoSource, string? Notes = null);

// Minimal canned client for deterministic tests / no-key runs.
// Returns pre-approved .ino sources for known capabilities so CreatorSimulation stays green and fast.
public sealed class CannedCreatorLlmClient : IChatClient
{
    public ChatClientMetadata Metadata { get; } = new("canned", null, null);

    public Task<ChatResponse> GetResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        // The user prompt contains the capability; we key off it for determinism.
        var userText = messages.LastOrDefault(m => m.Role == ChatRole.User)?.Text ?? string.Empty;
        var capability = ExtractCapability(userText);

        var ino = capability switch
        {
            "Generated.PingEcho" => """
neuron Generated.PingEcho
  "Generated by the v2 creator loop."

  using ping = synapse(Ping.Contracts.Ping)
  using pong = synapse(Ping.Contracts.Pong)

  broadcasts pong
  handles    ping

  state lastSeen: text

  on ping:
    set lastSeen = ping.from
    emit pong(to: ping.from)

scenario "generated ping is echoed"
  when  emit ping(from: "loop")
  then  broadcast pong observed with to == "loop"
""",
            _ => """
neuron Generated.PingEcho
  "Generated by the v2 creator loop."

  using ping = synapse(Ping.Contracts.Ping)
  using pong = synapse(Ping.Contracts.Pong)

  broadcasts pong
  handles    ping

  state lastSeen: text

  on ping:
    set lastSeen = ping.from
    emit pong(to: ping.from)

scenario "generated ping is echoed"
  when  emit ping(from: "loop")
  then  broadcast pong observed with to == "loop"
"""
        };

        var json = System.Text.Json.JsonSerializer.Serialize(new InoDraft(ino, "canned"));
        var message = new ChatMessage(ChatRole.Assistant, json);
        return Task.FromResult(new ChatResponse(message));
    }

    public async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var response = await GetResponseAsync(messages, options, cancellationToken);
        // POC: non-streaming path is primary (GetResponseAsync<T>); streaming is best-effort.
        yield break;
    }

    public object? GetService(Type serviceType, object? serviceKey = null) => null;

    public void Dispose() { }

    private static string ExtractCapability(string text)
    {
        // Heuristic: the prompt we build will contain the cap; fall back to default.
        const string marker = "capability '";
        var idx = text.IndexOf(marker, StringComparison.Ordinal);
        if (idx < 0) return "Generated.PingEcho";
        var start = idx + marker.Length;
        var end = text.IndexOf('\'', start);
        return end > start ? text[start..end] : "Generated.PingEcho";
    }
}