<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Orleans.Journaling" Version="10.2.2-rc.2.alpha.1" />
    <PackageVersion Include="Microsoft.Orleans.Reminders" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Serialization.SystemTextJson" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.TestingHost" Version="10.2.2" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>
</Project>
