<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Aspire AppHost integration for the DigitalBrain Qdrant vector store.</Description>
    <RootNamespace>DigitalBrain.Qdrant.Aspire.Hosting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Qdrant" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DigitalBrain.Modules.Qdrant/DigitalBrain.Modules.Qdrant.csproj" />
    <ProjectReference Include="../../DigitalBrain/Kernel/DigitalBrain.Kernel.Aspire.Hosting/DigitalBrain.Kernel.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
