<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Module/DigitalBrain.Testing.Module.csproj" />
    <ProjectReference Include="../../DigitalBrain.Modules.Salesforce/DigitalBrain.Modules.Salesforce.csproj" />
    <ProjectReference Include="../../../../DigitalBrain/Platform/DigitalBrain.Platform/DigitalBrain.Platform.csproj" />
  </ItemGroup>
  <ItemGroup><Using Include="DigitalBrain.Testing.Module" /></ItemGroup>
</Project>
