<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>true</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Flutter/DigitalBrain.Modules.Flutter.csproj" />
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
  </ItemGroup>
</Project>
