<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../../Testing/DigitalBrain.Testing.Integration/buildTransitive/DigitalBrain.Testing.Integration.targets" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <RootNamespace>IntoChat.Tests.E2E</RootNamespace>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Integration/DigitalBrain.Testing.Integration.csproj" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.Playwright" />
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
    <ProjectReference Include="../../../../Modules/Flutter/Testing/DigitalBrain.Modules.Flutter.Testing.csproj" />
    <ProjectReference Include="../../AppHost/IntoChat.AppHost.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../../IntoChat/IntoChat.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="testconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="DigitalBrain" />
    <Using Include="DigitalBrain.Testing.E2E" />
    <Using Include="DigitalBrain.Testing" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
