<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DigitalBrain</RootNamespace>
    <NoWarn>$(NoWarn);ORLEANSEXP005;CA2007;CA1812</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalBrain.Core\DigitalBrain.Core.csproj" />
    <InternalsVisibleTo Include="DigitalBrain.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Journaling" />
    <PackageReference Include="Microsoft.Orleans.Reminders" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <PackageReference Include="Microsoft.Orleans.Serialization.SystemTextJson" />
  </ItemGroup>
</Project>
