<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA2007;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalBrain.Modules.Flutter.Http\DigitalBrain.Modules.Flutter.Http.csproj" />
    <ProjectReference Include="..\DigitalBrain.Modules.Flutter\DigitalBrain.Modules.Flutter.csproj" />
    <ProjectReference Include="..\..\chat\DigitalBrain.Modules.Chat\DigitalBrain.Modules.Chat.csproj" />
    <ProjectReference Include="..\..\ai\DigitalBrain.Modules.AI\DigitalBrain.Modules.AI.csproj" />
    <ProjectReference Include="..\..\..\core\testing\DigitalBrain.Testing\DigitalBrain.Testing.csproj" />
    <ProjectReference Include="..\DigitalBrain.Modules.Flutter.Aspire.Hosting\DigitalBrain.Modules.Flutter.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
