<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Aspire hosting for the GitHub module.</Description>
    <RootNamespace>DigitalBrain.Modules.Microsoft.GitHub.Aspire.Hosting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DigitalBrain.Modules.Microsoft.GitHub.Contracts/DigitalBrain.Modules.Microsoft.GitHub.Contracts.csproj" />
    <ProjectReference Include="../../../../Aspire/DigitalBrain.Aspire.Hosting/DigitalBrain.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
