<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.E2E/DigitalBrain.Testing.E2E.csproj" />
    <ProjectReference Include="../../Google/DigitalBrain.Modules.Google.csproj" />
    <ProjectReference Include="../../Aspire.Hosting/DigitalBrain.Modules.Google.Aspire.Hosting.csproj" />
  </ItemGroup>
</Project>
