<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../DigitalBrain.Apps.CustomerResearcher.csproj" />
    <ProjectReference Include="../../../../Modules/DigitalBrain/Apps/DigitalBrain.Modules.Apps.Testing/DigitalBrain.Modules.Apps.Testing.csproj" />
    <ProjectReference Include="../../../../Testing/DigitalBrain.Testing.Unit/DigitalBrain.Testing.Unit.csproj" />
  </ItemGroup>
</Project>
