<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\core\aspire\DigitalBrain.Aspire\DigitalBrain.Aspire.csproj" />
    <ProjectReference Include="..\core\behaviors\DigitalBrain.Behaviors\DigitalBrain.Behaviors.csproj" />
    <ProjectReference Include="..\modules\ai\DigitalBrain.Modules.AI.Aspire.Hosting\DigitalBrain.Modules.AI.Aspire.Hosting.csproj" />
    <ProjectReference Include="..\modules\tasks\DigitalBrain.Modules.Tasks\DigitalBrain.Modules.Tasks.csproj" />
    <ProjectReference Include="..\modules\time\DigitalBrain.Modules.Time\DigitalBrain.Modules.Time.csproj" />
    <ProjectReference Include="..\modules\shell\DigitalBrain.Modules.Shell\DigitalBrain.Modules.Shell.csproj" />
    <ProjectReference Include="..\modules\shell\DigitalBrain.Modules.Shell.Aspire.Hosting\DigitalBrain.Modules.Shell.Aspire.Hosting.csproj" />
    <ProjectReference Include="..\modules\google\DigitalBrain.Modules.Google.Aspire.Hosting\DigitalBrain.Modules.Google.Aspire.Hosting.csproj" />
    <ProjectReference Include="..\modules\salesforce\DigitalBrain.Modules.Salesforce.Aspire.Hosting\DigitalBrain.Modules.Salesforce.Aspire.Hosting.csproj" />
    <ProjectReference Include="..\modules\memory\DigitalBrain.Modules.Memory.Contracts\DigitalBrain.Modules.Memory.Contracts.csproj" />
    <ProjectReference Include="..\modules\ai\DigitalBrain.Modules.AI\DigitalBrain.Modules.AI.csproj" />
    <ProjectReference Include="..\..\samples/DigitalBrain.AccountEnrichment\DigitalBrain.AccountEnrichment.csproj" />
  </ItemGroup>
</Project>
