<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Brain.Abstractions/Brain.Abstractions.csproj" />
    <ProjectReference Include="../Brain.Core/Brain.Core.csproj" />
    <ProjectReference Include="../Modules/Proof/Contracts/Brain.Modules.Proof.Contracts.csproj" />
    <ProjectReference Include="../Modules/Proof/Runtime/Brain.Modules.Proof.csproj" />
  </ItemGroup>
</Project>
